// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: client/client.proto

package client

import (
	common "github.com/daedaluz/mantra-cli/lib/grpc/common"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SignRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	User             string                 `protobuf:"bytes,2,opt,name=user,proto3" json:"user,omitempty"`
	Timeout          int64                  `protobuf:"varint,3,opt,name=timeout,proto3" json:"timeout,omitempty"`
	UserVerification string                 `protobuf:"bytes,4,opt,name=user_verification,json=userVerification,proto3" json:"user_verification,omitempty"`
	Mediation        string                 `protobuf:"bytes,5,opt,name=mediation,proto3" json:"mediation,omitempty"`
	Message          string                 `protobuf:"bytes,6,opt,name=message,proto3" json:"message,omitempty"`
	Data             []byte                 `protobuf:"bytes,7,opt,name=data,proto3" json:"data,omitempty"`
	ReturnUrl        string                 `protobuf:"bytes,8,opt,name=return_url,json=returnUrl,proto3" json:"return_url,omitempty"`
	Location         *common.Location       `protobuf:"bytes,9,opt,name=location,proto3" json:"location,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *SignRequest) Reset() {
	*x = SignRequest{}
	mi := &file_client_client_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SignRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SignRequest) ProtoMessage() {}

func (x *SignRequest) ProtoReflect() protoreflect.Message {
	mi := &file_client_client_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SignRequest.ProtoReflect.Descriptor instead.
func (*SignRequest) Descriptor() ([]byte, []int) {
	return file_client_client_proto_rawDescGZIP(), []int{0}
}

func (x *SignRequest) GetUser() string {
	if x != nil {
		return x.User
	}
	return ""
}

func (x *SignRequest) GetTimeout() int64 {
	if x != nil {
		return x.Timeout
	}
	return 0
}

func (x *SignRequest) GetUserVerification() string {
	if x != nil {
		return x.UserVerification
	}
	return ""
}

func (x *SignRequest) GetMediation() string {
	if x != nil {
		return x.Mediation
	}
	return ""
}

func (x *SignRequest) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *SignRequest) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *SignRequest) GetReturnUrl() string {
	if x != nil {
		return x.ReturnUrl
	}
	return ""
}

func (x *SignRequest) GetLocation() *common.Location {
	if x != nil {
		return x.Location
	}
	return nil
}

type CancelRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ChallengeId   string                 `protobuf:"bytes,1,opt,name=challenge_id,json=challengeId,proto3" json:"challenge_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelRequest) Reset() {
	*x = CancelRequest{}
	mi := &file_client_client_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelRequest) ProtoMessage() {}

func (x *CancelRequest) ProtoReflect() protoreflect.Message {
	mi := &file_client_client_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelRequest.ProtoReflect.Descriptor instead.
func (*CancelRequest) Descriptor() ([]byte, []int) {
	return file_client_client_proto_rawDescGZIP(), []int{1}
}

func (x *CancelRequest) GetChallengeId() string {
	if x != nil {
		return x.ChallengeId
	}
	return ""
}

type CollectRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	ChallengeId     string                 `protobuf:"bytes,1,opt,name=challenge_id,json=challengeId,proto3" json:"challenge_id,omitempty"`
	ChallengeSecret string                 `protobuf:"bytes,2,opt,name=challenge_secret,json=challengeSecret,proto3" json:"challenge_secret,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *CollectRequest) Reset() {
	*x = CollectRequest{}
	mi := &file_client_client_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CollectRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CollectRequest) ProtoMessage() {}

func (x *CollectRequest) ProtoReflect() protoreflect.Message {
	mi := &file_client_client_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CollectRequest.ProtoReflect.Descriptor instead.
func (*CollectRequest) Descriptor() ([]byte, []int) {
	return file_client_client_proto_rawDescGZIP(), []int{2}
}

func (x *CollectRequest) GetChallengeId() string {
	if x != nil {
		return x.ChallengeId
	}
	return ""
}

func (x *CollectRequest) GetChallengeSecret() string {
	if x != nil {
		return x.ChallengeSecret
	}
	return ""
}

type CollectResponse struct {
	state                   protoimpl.MessageState `protogen:"open.v1"`
	Status                  common.Status          `protobuf:"varint,1,opt,name=status,proto3,enum=se.mantra.api.common.Status" json:"status,omitempty"`
	SignedAt                *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=signed_at,json=signedAt,proto3" json:"signed_at,omitempty"`
	UserId                  string                 `protobuf:"bytes,3,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Message                 string                 `protobuf:"bytes,4,opt,name=message,proto3" json:"message,omitempty"`
	Data                    []byte                 `protobuf:"bytes,5,opt,name=data,proto3" json:"data,omitempty"`
	Challenge               []byte                 `protobuf:"bytes,6,opt,name=challenge,proto3" json:"challenge,omitempty"`
	KeyId                   []byte                 `protobuf:"bytes,8,opt,name=key_id,json=keyId,proto3" json:"key_id,omitempty"`
	AuthenticatorAttachment string                 `protobuf:"bytes,7,opt,name=authenticatorAttachment,proto3" json:"authenticatorAttachment,omitempty"`
	AuthenticatorData       []byte                 `protobuf:"bytes,9,opt,name=authenticatorData,proto3" json:"authenticatorData,omitempty"`
	ClientDataJson          []byte                 `protobuf:"bytes,10,opt,name=clientDataJson,proto3" json:"clientDataJson,omitempty"`
	Signature               []byte                 `protobuf:"bytes,11,opt,name=signature,proto3" json:"signature,omitempty"`
	Location                *common.Location       `protobuf:"bytes,12,opt,name=location,proto3" json:"location,omitempty"`
	PublicKey               []byte                 `protobuf:"bytes,13,opt,name=public_key,json=publicKey,proto3" json:"public_key,omitempty"`
	Algorithm               int64                  `protobuf:"varint,14,opt,name=algorithm,proto3" json:"algorithm,omitempty"`
	unknownFields           protoimpl.UnknownFields
	sizeCache               protoimpl.SizeCache
}

func (x *CollectResponse) Reset() {
	*x = CollectResponse{}
	mi := &file_client_client_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CollectResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CollectResponse) ProtoMessage() {}

func (x *CollectResponse) ProtoReflect() protoreflect.Message {
	mi := &file_client_client_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CollectResponse.ProtoReflect.Descriptor instead.
func (*CollectResponse) Descriptor() ([]byte, []int) {
	return file_client_client_proto_rawDescGZIP(), []int{3}
}

func (x *CollectResponse) GetStatus() common.Status {
	if x != nil {
		return x.Status
	}
	return common.Status(0)
}

func (x *CollectResponse) GetSignedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.SignedAt
	}
	return nil
}

func (x *CollectResponse) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *CollectResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *CollectResponse) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *CollectResponse) GetChallenge() []byte {
	if x != nil {
		return x.Challenge
	}
	return nil
}

func (x *CollectResponse) GetKeyId() []byte {
	if x != nil {
		return x.KeyId
	}
	return nil
}

func (x *CollectResponse) GetAuthenticatorAttachment() string {
	if x != nil {
		return x.AuthenticatorAttachment
	}
	return ""
}

func (x *CollectResponse) GetAuthenticatorData() []byte {
	if x != nil {
		return x.AuthenticatorData
	}
	return nil
}

func (x *CollectResponse) GetClientDataJson() []byte {
	if x != nil {
		return x.ClientDataJson
	}
	return nil
}

func (x *CollectResponse) GetSignature() []byte {
	if x != nil {
		return x.Signature
	}
	return nil
}

func (x *CollectResponse) GetLocation() *common.Location {
	if x != nil {
		return x.Location
	}
	return nil
}

func (x *CollectResponse) GetPublicKey() []byte {
	if x != nil {
		return x.PublicKey
	}
	return nil
}

func (x *CollectResponse) GetAlgorithm() int64 {
	if x != nil {
		return x.Algorithm
	}
	return 0
}

var File_client_client_proto protoreflect.FileDescriptor

const file_client_client_proto_rawDesc = "" +
	"\n" +
	"\x13client/client.proto\x12\x14se.mantra.api.client\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1bgoogle/protobuf/empty.proto\x1a\x13common/common.proto\"\x8f\x02\n" +
	"\vSignRequest\x12\x12\n" +
	"\x04user\x18\x02 \x01(\tR\x04user\x12\x18\n" +
	"\atimeout\x18\x03 \x01(\x03R\atimeout\x12+\n" +
	"\x11user_verification\x18\x04 \x01(\tR\x10userVerification\x12\x1c\n" +
	"\tmediation\x18\x05 \x01(\tR\tmediation\x12\x18\n" +
	"\amessage\x18\x06 \x01(\tR\amessage\x12\x12\n" +
	"\x04data\x18\a \x01(\fR\x04data\x12\x1d\n" +
	"\n" +
	"return_url\x18\b \x01(\tR\treturnUrl\x12:\n" +
	"\blocation\x18\t \x01(\v2\x1e.se.mantra.api.common.LocationR\blocation\"2\n" +
	"\rCancelRequest\x12!\n" +
	"\fchallenge_id\x18\x01 \x01(\tR\vchallengeId\"^\n" +
	"\x0eCollectRequest\x12!\n" +
	"\fchallenge_id\x18\x01 \x01(\tR\vchallengeId\x12)\n" +
	"\x10challenge_secret\x18\x02 \x01(\tR\x0fchallengeSecret\"\xa3\x04\n" +
	"\x0fCollectResponse\x124\n" +
	"\x06status\x18\x01 \x01(\x0e2\x1c.se.mantra.api.common.StatusR\x06status\x127\n" +
	"\tsigned_at\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\bsignedAt\x12\x17\n" +
	"\auser_id\x18\x03 \x01(\tR\x06userId\x12\x18\n" +
	"\amessage\x18\x04 \x01(\tR\amessage\x12\x12\n" +
	"\x04data\x18\x05 \x01(\fR\x04data\x12\x1c\n" +
	"\tchallenge\x18\x06 \x01(\fR\tchallenge\x12\x15\n" +
	"\x06key_id\x18\b \x01(\fR\x05keyId\x128\n" +
	"\x17authenticatorAttachment\x18\a \x01(\tR\x17authenticatorAttachment\x12,\n" +
	"\x11authenticatorData\x18\t \x01(\fR\x11authenticatorData\x12&\n" +
	"\x0eclientDataJson\x18\n" +
	" \x01(\fR\x0eclientDataJson\x12\x1c\n" +
	"\tsignature\x18\v \x01(\fR\tsignature\x12:\n" +
	"\blocation\x18\f \x01(\v2\x1e.se.mantra.api.common.LocationR\blocation\x12\x1d\n" +
	"\n" +
	"public_key\x18\r \x01(\fR\tpublicKey\x12\x1c\n" +
	"\talgorithm\x18\x0e \x01(\x03R\talgorithm2\x82\x02\n" +
	"\rClientService\x12R\n" +
	"\x04Sign\x12!.se.mantra.api.client.SignRequest\x1a'.se.mantra.api.common.ChallengeResponse\x12E\n" +
	"\x06Cancel\x12#.se.mantra.api.client.CancelRequest\x1a\x16.google.protobuf.Empty\x12V\n" +
	"\aCollect\x12$.se.mantra.api.client.CollectRequest\x1a%.se.mantra.api.client.CollectResponseB0Z.github.com/daedaluz/mantra-cli/lib/grpc/clientb\x06proto3"

var (
	file_client_client_proto_rawDescOnce sync.Once
	file_client_client_proto_rawDescData []byte
)

func file_client_client_proto_rawDescGZIP() []byte {
	file_client_client_proto_rawDescOnce.Do(func() {
		file_client_client_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_client_client_proto_rawDesc), len(file_client_client_proto_rawDesc)))
	})
	return file_client_client_proto_rawDescData
}

var file_client_client_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_client_client_proto_goTypes = []any{
	(*SignRequest)(nil),              // 0: se.mantra.api.client.SignRequest
	(*CancelRequest)(nil),            // 1: se.mantra.api.client.CancelRequest
	(*CollectRequest)(nil),           // 2: se.mantra.api.client.CollectRequest
	(*CollectResponse)(nil),          // 3: se.mantra.api.client.CollectResponse
	(*common.Location)(nil),          // 4: se.mantra.api.common.Location
	(common.Status)(0),               // 5: se.mantra.api.common.Status
	(*timestamppb.Timestamp)(nil),    // 6: google.protobuf.Timestamp
	(*common.ChallengeResponse)(nil), // 7: se.mantra.api.common.ChallengeResponse
	(*emptypb.Empty)(nil),            // 8: google.protobuf.Empty
}
var file_client_client_proto_depIdxs = []int32{
	4, // 0: se.mantra.api.client.SignRequest.location:type_name -> se.mantra.api.common.Location
	5, // 1: se.mantra.api.client.CollectResponse.status:type_name -> se.mantra.api.common.Status
	6, // 2: se.mantra.api.client.CollectResponse.signed_at:type_name -> google.protobuf.Timestamp
	4, // 3: se.mantra.api.client.CollectResponse.location:type_name -> se.mantra.api.common.Location
	0, // 4: se.mantra.api.client.ClientService.Sign:input_type -> se.mantra.api.client.SignRequest
	1, // 5: se.mantra.api.client.ClientService.Cancel:input_type -> se.mantra.api.client.CancelRequest
	2, // 6: se.mantra.api.client.ClientService.Collect:input_type -> se.mantra.api.client.CollectRequest
	7, // 7: se.mantra.api.client.ClientService.Sign:output_type -> se.mantra.api.common.ChallengeResponse
	8, // 8: se.mantra.api.client.ClientService.Cancel:output_type -> google.protobuf.Empty
	3, // 9: se.mantra.api.client.ClientService.Collect:output_type -> se.mantra.api.client.CollectResponse
	7, // [7:10] is the sub-list for method output_type
	4, // [4:7] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_client_client_proto_init() }
func file_client_client_proto_init() {
	if File_client_client_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_client_client_proto_rawDesc), len(file_client_client_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_client_client_proto_goTypes,
		DependencyIndexes: file_client_client_proto_depIdxs,
		MessageInfos:      file_client_client_proto_msgTypes,
	}.Build()
	File_client_client_proto = out.File
	file_client_client_proto_goTypes = nil
	file_client_client_proto_depIdxs = nil
}
