// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: common/common.proto

package common

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	_ "google.golang.org/protobuf/types/known/emptypb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Status int32

const (
	Status_Unspecified Status = 0
	Status_Pending     Status = 1
	Status_Seen        Status = 2
	Status_Completed   Status = 3
	Status_Collected   Status = 4
	Status_Cancelled   Status = 5
	Status_Rejected    Status = 6
	Status_Expired     Status = 7
)

// Enum value maps for Status.
var (
	Status_name = map[int32]string{
		0: "Unspecified",
		1: "Pending",
		2: "Seen",
		3: "Completed",
		4: "Collected",
		5: "Cancelled",
		6: "Rejected",
		7: "Expired",
	}
	Status_value = map[string]int32{
		"Unspecified": 0,
		"Pending":     1,
		"Seen":        2,
		"Completed":   3,
		"Collected":   4,
		"Cancelled":   5,
		"Rejected":    6,
		"Expired":     7,
	}
)

func (x Status) Enum() *Status {
	p := new(Status)
	*p = x
	return p
}

func (x Status) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Status) Descriptor() protoreflect.EnumDescriptor {
	return file_common_common_proto_enumTypes[0].Descriptor()
}

func (Status) Type() protoreflect.EnumType {
	return &file_common_common_proto_enumTypes[0]
}

func (x Status) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Status.Descriptor instead.
func (Status) EnumDescriptor() ([]byte, []int) {
	return file_common_common_proto_rawDescGZIP(), []int{0}
}

type ChallengeResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	ChallengeId     string                 `protobuf:"bytes,1,opt,name=challenge_id,json=challengeId,proto3" json:"challenge_id,omitempty"`
	ChallengeData   string                 `protobuf:"bytes,2,opt,name=challenge_data,json=challengeData,proto3" json:"challenge_data,omitempty"`
	ChallengeSecret string                 `protobuf:"bytes,3,opt,name=challenge_secret,json=challengeSecret,proto3" json:"challenge_secret,omitempty"`
	ExpiresAt       *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
	// If location is set, frontend should request location from user-agent and include it with the signature.
	Location      *Location `protobuf:"bytes,5,opt,name=location,proto3" json:"location,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChallengeResponse) Reset() {
	*x = ChallengeResponse{}
	mi := &file_common_common_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChallengeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChallengeResponse) ProtoMessage() {}

func (x *ChallengeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_common_common_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChallengeResponse.ProtoReflect.Descriptor instead.
func (*ChallengeResponse) Descriptor() ([]byte, []int) {
	return file_common_common_proto_rawDescGZIP(), []int{0}
}

func (x *ChallengeResponse) GetChallengeId() string {
	if x != nil {
		return x.ChallengeId
	}
	return ""
}

func (x *ChallengeResponse) GetChallengeData() string {
	if x != nil {
		return x.ChallengeData
	}
	return ""
}

func (x *ChallengeResponse) GetChallengeSecret() string {
	if x != nil {
		return x.ChallengeSecret
	}
	return ""
}

func (x *ChallengeResponse) GetExpiresAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ExpiresAt
	}
	return nil
}

func (x *ChallengeResponse) GetLocation() *Location {
	if x != nil {
		return x.Location
	}
	return nil
}

type Key struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	CreatedAt       *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	LastUsed        *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=last_used,json=lastUsed,proto3" json:"last_used,omitempty"`
	Revoked         bool                   `protobuf:"varint,3,opt,name=revoked,proto3" json:"revoked,omitempty"`
	Pending         bool                   `protobuf:"varint,18,opt,name=pending,proto3" json:"pending,omitempty"`
	Name            string                 `protobuf:"bytes,4,opt,name=name,proto3" json:"name,omitempty"`
	KeyId           []byte                 `protobuf:"bytes,5,opt,name=key_id,json=keyId,proto3" json:"key_id,omitempty"`
	Algorithm       int64                  `protobuf:"varint,6,opt,name=algorithm,proto3" json:"algorithm,omitempty"`
	Attachment      string                 `protobuf:"bytes,7,opt,name=attachment,proto3" json:"attachment,omitempty"`
	PublicKey       []byte                 `protobuf:"bytes,8,opt,name=public_key,json=publicKey,proto3" json:"public_key,omitempty"`
	AttestationType string                 `protobuf:"bytes,9,opt,name=attestation_type,json=attestationType,proto3" json:"attestation_type,omitempty"`
	Aaguid          []byte                 `protobuf:"bytes,10,opt,name=aaguid,proto3" json:"aaguid,omitempty"`
	SignCount       int64                  `protobuf:"varint,11,opt,name=sign_count,json=signCount,proto3" json:"sign_count,omitempty"`
	CloneWarning    bool                   `protobuf:"varint,12,opt,name=clone_warning,json=cloneWarning,proto3" json:"clone_warning,omitempty"`
	UserVerified    bool                   `protobuf:"varint,13,opt,name=user_verified,json=userVerified,proto3" json:"user_verified,omitempty"`
	UserPresent     bool                   `protobuf:"varint,14,opt,name=user_present,json=userPresent,proto3" json:"user_present,omitempty"`
	BackupEligible  bool                   `protobuf:"varint,15,opt,name=backup_eligible,json=backupEligible,proto3" json:"backup_eligible,omitempty"`
	BackedUp        bool                   `protobuf:"varint,16,opt,name=backed_up,json=backedUp,proto3" json:"backed_up,omitempty"`
	Transports      []string               `protobuf:"bytes,17,rep,name=transports,proto3" json:"transports,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *Key) Reset() {
	*x = Key{}
	mi := &file_common_common_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Key) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Key) ProtoMessage() {}

func (x *Key) ProtoReflect() protoreflect.Message {
	mi := &file_common_common_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Key.ProtoReflect.Descriptor instead.
func (*Key) Descriptor() ([]byte, []int) {
	return file_common_common_proto_rawDescGZIP(), []int{1}
}

func (x *Key) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Key) GetLastUsed() *timestamppb.Timestamp {
	if x != nil {
		return x.LastUsed
	}
	return nil
}

func (x *Key) GetRevoked() bool {
	if x != nil {
		return x.Revoked
	}
	return false
}

func (x *Key) GetPending() bool {
	if x != nil {
		return x.Pending
	}
	return false
}

func (x *Key) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Key) GetKeyId() []byte {
	if x != nil {
		return x.KeyId
	}
	return nil
}

func (x *Key) GetAlgorithm() int64 {
	if x != nil {
		return x.Algorithm
	}
	return 0
}

func (x *Key) GetAttachment() string {
	if x != nil {
		return x.Attachment
	}
	return ""
}

func (x *Key) GetPublicKey() []byte {
	if x != nil {
		return x.PublicKey
	}
	return nil
}

func (x *Key) GetAttestationType() string {
	if x != nil {
		return x.AttestationType
	}
	return ""
}

func (x *Key) GetAaguid() []byte {
	if x != nil {
		return x.Aaguid
	}
	return nil
}

func (x *Key) GetSignCount() int64 {
	if x != nil {
		return x.SignCount
	}
	return 0
}

func (x *Key) GetCloneWarning() bool {
	if x != nil {
		return x.CloneWarning
	}
	return false
}

func (x *Key) GetUserVerified() bool {
	if x != nil {
		return x.UserVerified
	}
	return false
}

func (x *Key) GetUserPresent() bool {
	if x != nil {
		return x.UserPresent
	}
	return false
}

func (x *Key) GetBackupEligible() bool {
	if x != nil {
		return x.BackupEligible
	}
	return false
}

func (x *Key) GetBackedUp() bool {
	if x != nil {
		return x.BackedUp
	}
	return false
}

func (x *Key) GetTransports() []string {
	if x != nil {
		return x.Transports
	}
	return nil
}

type ClientMeta struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ClientId      string                 `protobuf:"bytes,1,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	ClientSecret  string                 `protobuf:"bytes,2,opt,name=client_secret,json=clientSecret,proto3" json:"client_secret,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Icon          string                 `protobuf:"bytes,4,opt,name=icon,proto3" json:"icon,omitempty"`
	Description   string                 `protobuf:"bytes,5,opt,name=description,proto3" json:"description,omitempty"`
	Admin         bool                   `protobuf:"varint,6,opt,name=admin,proto3" json:"admin,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClientMeta) Reset() {
	*x = ClientMeta{}
	mi := &file_common_common_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClientMeta) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientMeta) ProtoMessage() {}

func (x *ClientMeta) ProtoReflect() protoreflect.Message {
	mi := &file_common_common_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientMeta.ProtoReflect.Descriptor instead.
func (*ClientMeta) Descriptor() ([]byte, []int) {
	return file_common_common_proto_rawDescGZIP(), []int{2}
}

func (x *ClientMeta) GetClientId() string {
	if x != nil {
		return x.ClientId
	}
	return ""
}

func (x *ClientMeta) GetClientSecret() string {
	if x != nil {
		return x.ClientSecret
	}
	return ""
}

func (x *ClientMeta) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ClientMeta) GetIcon() string {
	if x != nil {
		return x.Icon
	}
	return ""
}

func (x *ClientMeta) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *ClientMeta) GetAdmin() bool {
	if x != nil {
		return x.Admin
	}
	return false
}

func (x *ClientMeta) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

type LongLatitude struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Latitude      float64                `protobuf:"fixed64,1,opt,name=latitude,proto3" json:"latitude,omitempty"`
	Longitude     float64                `protobuf:"fixed64,2,opt,name=longitude,proto3" json:"longitude,omitempty"`
	Accuracy      float64                `protobuf:"fixed64,3,opt,name=accuracy,proto3" json:"accuracy,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LongLatitude) Reset() {
	*x = LongLatitude{}
	mi := &file_common_common_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LongLatitude) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LongLatitude) ProtoMessage() {}

func (x *LongLatitude) ProtoReflect() protoreflect.Message {
	mi := &file_common_common_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LongLatitude.ProtoReflect.Descriptor instead.
func (*LongLatitude) Descriptor() ([]byte, []int) {
	return file_common_common_proto_rawDescGZIP(), []int{3}
}

func (x *LongLatitude) GetLatitude() float64 {
	if x != nil {
		return x.Latitude
	}
	return 0
}

func (x *LongLatitude) GetLongitude() float64 {
	if x != nil {
		return x.Longitude
	}
	return 0
}

func (x *LongLatitude) GetAccuracy() float64 {
	if x != nil {
		return x.Accuracy
	}
	return 0
}

type Location struct {
	state    protoimpl.MessageState `protogen:"open.v1"`
	Ip       string                 `protobuf:"bytes,1,opt,name=ip,proto3" json:"ip,omitempty"`
	Geohash  string                 `protobuf:"bytes,2,opt,name=geohash,proto3" json:"geohash,omitempty"`
	Position *LongLatitude          `protobuf:"bytes,3,opt,name=position,proto3" json:"position,omitempty"`
	// If required is true, backend will verify the signature location matches before accepting.
	// If required is false, backend will only store the location without verification.
	Required      bool `protobuf:"varint,4,opt,name=required,proto3" json:"required,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Location) Reset() {
	*x = Location{}
	mi := &file_common_common_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Location) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Location) ProtoMessage() {}

func (x *Location) ProtoReflect() protoreflect.Message {
	mi := &file_common_common_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Location.ProtoReflect.Descriptor instead.
func (*Location) Descriptor() ([]byte, []int) {
	return file_common_common_proto_rawDescGZIP(), []int{4}
}

func (x *Location) GetIp() string {
	if x != nil {
		return x.Ip
	}
	return ""
}

func (x *Location) GetGeohash() string {
	if x != nil {
		return x.Geohash
	}
	return ""
}

func (x *Location) GetPosition() *LongLatitude {
	if x != nil {
		return x.Position
	}
	return nil
}

func (x *Location) GetRequired() bool {
	if x != nil {
		return x.Required
	}
	return false
}

var File_common_common_proto protoreflect.FileDescriptor

const file_common_common_proto_rawDesc = "" +
	"\n" +
	"\x13common/common.proto\x12\x14se.mantra.api.common\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1bgoogle/protobuf/empty.proto\"\xff\x01\n" +
	"\x11ChallengeResponse\x12!\n" +
	"\fchallenge_id\x18\x01 \x01(\tR\vchallengeId\x12%\n" +
	"\x0echallenge_data\x18\x02 \x01(\tR\rchallengeData\x12)\n" +
	"\x10challenge_secret\x18\x03 \x01(\tR\x0fchallengeSecret\x129\n" +
	"\n" +
	"expires_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\texpiresAt\x12:\n" +
	"\blocation\x18\x05 \x01(\v2\x1e.se.mantra.api.common.LocationR\blocation\"\xea\x04\n" +
	"\x03Key\x129\n" +
	"\n" +
	"created_at\x18\x01 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x127\n" +
	"\tlast_used\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\blastUsed\x12\x18\n" +
	"\arevoked\x18\x03 \x01(\bR\arevoked\x12\x18\n" +
	"\apending\x18\x12 \x01(\bR\apending\x12\x12\n" +
	"\x04name\x18\x04 \x01(\tR\x04name\x12\x15\n" +
	"\x06key_id\x18\x05 \x01(\fR\x05keyId\x12\x1c\n" +
	"\talgorithm\x18\x06 \x01(\x03R\talgorithm\x12\x1e\n" +
	"\n" +
	"attachment\x18\a \x01(\tR\n" +
	"attachment\x12\x1d\n" +
	"\n" +
	"public_key\x18\b \x01(\fR\tpublicKey\x12)\n" +
	"\x10attestation_type\x18\t \x01(\tR\x0fattestationType\x12\x16\n" +
	"\x06aaguid\x18\n" +
	" \x01(\fR\x06aaguid\x12\x1d\n" +
	"\n" +
	"sign_count\x18\v \x01(\x03R\tsignCount\x12#\n" +
	"\rclone_warning\x18\f \x01(\bR\fcloneWarning\x12#\n" +
	"\ruser_verified\x18\r \x01(\bR\fuserVerified\x12!\n" +
	"\fuser_present\x18\x0e \x01(\bR\vuserPresent\x12'\n" +
	"\x0fbackup_eligible\x18\x0f \x01(\bR\x0ebackupEligible\x12\x1b\n" +
	"\tbacked_up\x18\x10 \x01(\bR\bbackedUp\x12\x1e\n" +
	"\n" +
	"transports\x18\x11 \x03(\tR\n" +
	"transports\"\xe9\x01\n" +
	"\n" +
	"ClientMeta\x12\x1b\n" +
	"\tclient_id\x18\x01 \x01(\tR\bclientId\x12#\n" +
	"\rclient_secret\x18\x02 \x01(\tR\fclientSecret\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12\x12\n" +
	"\x04icon\x18\x04 \x01(\tR\x04icon\x12 \n" +
	"\vdescription\x18\x05 \x01(\tR\vdescription\x12\x14\n" +
	"\x05admin\x18\x06 \x01(\bR\x05admin\x129\n" +
	"\n" +
	"created_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\"d\n" +
	"\fLongLatitude\x12\x1a\n" +
	"\blatitude\x18\x01 \x01(\x01R\blatitude\x12\x1c\n" +
	"\tlongitude\x18\x02 \x01(\x01R\tlongitude\x12\x1a\n" +
	"\baccuracy\x18\x03 \x01(\x01R\baccuracy\"\x90\x01\n" +
	"\bLocation\x12\x0e\n" +
	"\x02ip\x18\x01 \x01(\tR\x02ip\x12\x18\n" +
	"\ageohash\x18\x02 \x01(\tR\ageohash\x12>\n" +
	"\bposition\x18\x03 \x01(\v2\".se.mantra.api.common.LongLatitudeR\bposition\x12\x1a\n" +
	"\brequired\x18\x04 \x01(\bR\brequired*x\n" +
	"\x06Status\x12\x0f\n" +
	"\vUnspecified\x10\x00\x12\v\n" +
	"\aPending\x10\x01\x12\b\n" +
	"\x04Seen\x10\x02\x12\r\n" +
	"\tCompleted\x10\x03\x12\r\n" +
	"\tCollected\x10\x04\x12\r\n" +
	"\tCancelled\x10\x05\x12\f\n" +
	"\bRejected\x10\x06\x12\v\n" +
	"\aExpired\x10\aB0Z.github.com/daedaluz/mantra-cli/lib/grpc/commonb\x06proto3"

var (
	file_common_common_proto_rawDescOnce sync.Once
	file_common_common_proto_rawDescData []byte
)

func file_common_common_proto_rawDescGZIP() []byte {
	file_common_common_proto_rawDescOnce.Do(func() {
		file_common_common_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_common_common_proto_rawDesc), len(file_common_common_proto_rawDesc)))
	})
	return file_common_common_proto_rawDescData
}

var file_common_common_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_common_common_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_common_common_proto_goTypes = []any{
	(Status)(0),                   // 0: se.mantra.api.common.Status
	(*ChallengeResponse)(nil),     // 1: se.mantra.api.common.ChallengeResponse
	(*Key)(nil),                   // 2: se.mantra.api.common.Key
	(*ClientMeta)(nil),            // 3: se.mantra.api.common.ClientMeta
	(*LongLatitude)(nil),          // 4: se.mantra.api.common.LongLatitude
	(*Location)(nil),              // 5: se.mantra.api.common.Location
	(*timestamppb.Timestamp)(nil), // 6: google.protobuf.Timestamp
}
var file_common_common_proto_depIdxs = []int32{
	6, // 0: se.mantra.api.common.ChallengeResponse.expires_at:type_name -> google.protobuf.Timestamp
	5, // 1: se.mantra.api.common.ChallengeResponse.location:type_name -> se.mantra.api.common.Location
	6, // 2: se.mantra.api.common.Key.created_at:type_name -> google.protobuf.Timestamp
	6, // 3: se.mantra.api.common.Key.last_used:type_name -> google.protobuf.Timestamp
	6, // 4: se.mantra.api.common.ClientMeta.created_at:type_name -> google.protobuf.Timestamp
	4, // 5: se.mantra.api.common.Location.position:type_name -> se.mantra.api.common.LongLatitude
	6, // [6:6] is the sub-list for method output_type
	6, // [6:6] is the sub-list for method input_type
	6, // [6:6] is the sub-list for extension type_name
	6, // [6:6] is the sub-list for extension extendee
	0, // [0:6] is the sub-list for field type_name
}

func init() { file_common_common_proto_init() }
func file_common_common_proto_init() {
	if File_common_common_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_common_common_proto_rawDesc), len(file_common_common_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_common_common_proto_goTypes,
		DependencyIndexes: file_common_common_proto_depIdxs,
		EnumInfos:         file_common_common_proto_enumTypes,
		MessageInfos:      file_common_common_proto_msgTypes,
	}.Build()
	File_common_common_proto = out.File
	file_common_common_proto_goTypes = nil
	file_common_common_proto_depIdxs = nil
}
