// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: public/auth.proto

package public

import (
	common "github.com/daedaluz/mantra-cli/lib/grpc/common"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	_ "google.golang.org/protobuf/types/known/emptypb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AllowedCredential struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            []byte                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Transports    []string               `protobuf:"bytes,3,rep,name=transports,proto3" json:"transports,omitempty"` // e.g. "usb", "nfc", "ble", "internal"
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AllowedCredential) Reset() {
	*x = AllowedCredential{}
	mi := &file_public_auth_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AllowedCredential) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AllowedCredential) ProtoMessage() {}

func (x *AllowedCredential) ProtoReflect() protoreflect.Message {
	mi := &file_public_auth_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AllowedCredential.ProtoReflect.Descriptor instead.
func (*AllowedCredential) Descriptor() ([]byte, []int) {
	return file_public_auth_proto_rawDescGZIP(), []int{0}
}

func (x *AllowedCredential) GetId() []byte {
	if x != nil {
		return x.Id
	}
	return nil
}

func (x *AllowedCredential) GetTransports() []string {
	if x != nil {
		return x.Transports
	}
	return nil
}

type GetChallengeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         string                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	DeviceId      string                 `protobuf:"bytes,2,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetChallengeRequest) Reset() {
	*x = GetChallengeRequest{}
	mi := &file_public_auth_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetChallengeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetChallengeRequest) ProtoMessage() {}

func (x *GetChallengeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_public_auth_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetChallengeRequest.ProtoReflect.Descriptor instead.
func (*GetChallengeRequest) Descriptor() ([]byte, []int) {
	return file_public_auth_proto_rawDescGZIP(), []int{1}
}

func (x *GetChallengeRequest) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *GetChallengeRequest) GetDeviceId() string {
	if x != nil {
		return x.DeviceId
	}
	return ""
}

type ChallengeResponse struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	Client             *common.ClientMeta     `protobuf:"bytes,1,opt,name=client,proto3" json:"client,omitempty"`
	Title              string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Icon               string                 `protobuf:"bytes,3,opt,name=icon,proto3" json:"icon,omitempty"`
	Message            string                 `protobuf:"bytes,4,opt,name=message,proto3" json:"message,omitempty"`
	Data               []byte                 `protobuf:"bytes,5,opt,name=data,proto3" json:"data,omitempty"`
	ChallengeId        string                 `protobuf:"bytes,12,opt,name=challenge_id,json=challengeId,proto3" json:"challenge_id,omitempty"`
	Challenge          []byte                 `protobuf:"bytes,6,opt,name=challenge,proto3" json:"challenge,omitempty"`
	RpId               string                 `protobuf:"bytes,7,opt,name=rp_id,json=rpId,proto3" json:"rp_id,omitempty"`
	AllowedCredentials []*AllowedCredential   `protobuf:"bytes,8,rep,name=allowed_credentials,json=allowedCredentials,proto3" json:"allowed_credentials,omitempty"`
	UserVerification   string                 `protobuf:"bytes,9,opt,name=user_verification,json=userVerification,proto3" json:"user_verification,omitempty"`
	Mediation          string                 `protobuf:"bytes,10,opt,name=mediation,proto3" json:"mediation,omitempty"`
	ExpiresAt          *timestamppb.Timestamp `protobuf:"bytes,11,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
	// Location where the signature request was initiated.
	// Frontend can use this to warn user about potential malicious activity.
	Location      *common.Location       `protobuf:"bytes,13,opt,name=location,proto3" json:"location,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,14,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	SignedAt      *timestamppb.Timestamp `protobuf:"bytes,15,opt,name=signed_at,json=signedAt,proto3" json:"signed_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChallengeResponse) Reset() {
	*x = ChallengeResponse{}
	mi := &file_public_auth_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChallengeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChallengeResponse) ProtoMessage() {}

func (x *ChallengeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_public_auth_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChallengeResponse.ProtoReflect.Descriptor instead.
func (*ChallengeResponse) Descriptor() ([]byte, []int) {
	return file_public_auth_proto_rawDescGZIP(), []int{2}
}

func (x *ChallengeResponse) GetClient() *common.ClientMeta {
	if x != nil {
		return x.Client
	}
	return nil
}

func (x *ChallengeResponse) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *ChallengeResponse) GetIcon() string {
	if x != nil {
		return x.Icon
	}
	return ""
}

func (x *ChallengeResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ChallengeResponse) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *ChallengeResponse) GetChallengeId() string {
	if x != nil {
		return x.ChallengeId
	}
	return ""
}

func (x *ChallengeResponse) GetChallenge() []byte {
	if x != nil {
		return x.Challenge
	}
	return nil
}

func (x *ChallengeResponse) GetRpId() string {
	if x != nil {
		return x.RpId
	}
	return ""
}

func (x *ChallengeResponse) GetAllowedCredentials() []*AllowedCredential {
	if x != nil {
		return x.AllowedCredentials
	}
	return nil
}

func (x *ChallengeResponse) GetUserVerification() string {
	if x != nil {
		return x.UserVerification
	}
	return ""
}

func (x *ChallengeResponse) GetMediation() string {
	if x != nil {
		return x.Mediation
	}
	return ""
}

func (x *ChallengeResponse) GetExpiresAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ExpiresAt
	}
	return nil
}

func (x *ChallengeResponse) GetLocation() *common.Location {
	if x != nil {
		return x.Location
	}
	return nil
}

func (x *ChallengeResponse) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *ChallengeResponse) GetSignedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.SignedAt
	}
	return nil
}

type SignRequest struct {
	state                   protoimpl.MessageState `protogen:"open.v1"`
	ChallengeId             string                 `protobuf:"bytes,1,opt,name=challenge_id,json=challengeId,proto3" json:"challenge_id,omitempty"`
	AuthenticatorAttachment string                 `protobuf:"bytes,2,opt,name=authenticator_attachment,json=authenticatorAttachment,proto3" json:"authenticator_attachment,omitempty"`
	Id                      string                 `protobuf:"bytes,3,opt,name=id,proto3" json:"id,omitempty"`
	RawId                   []byte                 `protobuf:"bytes,4,opt,name=rawId,proto3" json:"rawId,omitempty"`
	AuthenticatorData       []byte                 `protobuf:"bytes,5,opt,name=authenticator_data,json=authenticatorData,proto3" json:"authenticator_data,omitempty"`
	ClientDataJson          []byte                 `protobuf:"bytes,6,opt,name=client_data_json,json=clientDataJson,proto3" json:"client_data_json,omitempty"`
	Signature               []byte                 `protobuf:"bytes,7,opt,name=signature,proto3" json:"signature,omitempty"`
	UserHandle              []byte                 `protobuf:"bytes,8,opt,name=user_handle,json=userHandle,proto3" json:"user_handle,omitempty"`
	Location                *common.Location       `protobuf:"bytes,9,opt,name=location,proto3" json:"location,omitempty"`
	DeviceId                string                 `protobuf:"bytes,10,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"`
	unknownFields           protoimpl.UnknownFields
	sizeCache               protoimpl.SizeCache
}

func (x *SignRequest) Reset() {
	*x = SignRequest{}
	mi := &file_public_auth_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SignRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SignRequest) ProtoMessage() {}

func (x *SignRequest) ProtoReflect() protoreflect.Message {
	mi := &file_public_auth_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SignRequest.ProtoReflect.Descriptor instead.
func (*SignRequest) Descriptor() ([]byte, []int) {
	return file_public_auth_proto_rawDescGZIP(), []int{3}
}

func (x *SignRequest) GetChallengeId() string {
	if x != nil {
		return x.ChallengeId
	}
	return ""
}

func (x *SignRequest) GetAuthenticatorAttachment() string {
	if x != nil {
		return x.AuthenticatorAttachment
	}
	return ""
}

func (x *SignRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *SignRequest) GetRawId() []byte {
	if x != nil {
		return x.RawId
	}
	return nil
}

func (x *SignRequest) GetAuthenticatorData() []byte {
	if x != nil {
		return x.AuthenticatorData
	}
	return nil
}

func (x *SignRequest) GetClientDataJson() []byte {
	if x != nil {
		return x.ClientDataJson
	}
	return nil
}

func (x *SignRequest) GetSignature() []byte {
	if x != nil {
		return x.Signature
	}
	return nil
}

func (x *SignRequest) GetUserHandle() []byte {
	if x != nil {
		return x.UserHandle
	}
	return nil
}

func (x *SignRequest) GetLocation() *common.Location {
	if x != nil {
		return x.Location
	}
	return nil
}

func (x *SignRequest) GetDeviceId() string {
	if x != nil {
		return x.DeviceId
	}
	return ""
}

type SignResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DeviceId      string                 `protobuf:"bytes,1,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SignResponse) Reset() {
	*x = SignResponse{}
	mi := &file_public_auth_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SignResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SignResponse) ProtoMessage() {}

func (x *SignResponse) ProtoReflect() protoreflect.Message {
	mi := &file_public_auth_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SignResponse.ProtoReflect.Descriptor instead.
func (*SignResponse) Descriptor() ([]byte, []int) {
	return file_public_auth_proto_rawDescGZIP(), []int{4}
}

func (x *SignResponse) GetDeviceId() string {
	if x != nil {
		return x.DeviceId
	}
	return ""
}

var File_public_auth_proto protoreflect.FileDescriptor

const file_public_auth_proto_rawDesc = "" +
	"\n" +
	"\x11public/auth.proto\x12\x14se.mantra.api.public\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1bgoogle/protobuf/empty.proto\x1a\x13common/common.proto\"C\n" +
	"\x11AllowedCredential\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\fR\x02id\x12\x1e\n" +
	"\n" +
	"transports\x18\x03 \x03(\tR\n" +
	"transports\"H\n" +
	"\x13GetChallengeRequest\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token\x12\x1b\n" +
	"\tdevice_id\x18\x02 \x01(\tR\bdeviceId\"\x8b\x05\n" +
	"\x11ChallengeResponse\x128\n" +
	"\x06client\x18\x01 \x01(\v2 .se.mantra.api.common.ClientMetaR\x06client\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12\x12\n" +
	"\x04icon\x18\x03 \x01(\tR\x04icon\x12\x18\n" +
	"\amessage\x18\x04 \x01(\tR\amessage\x12\x12\n" +
	"\x04data\x18\x05 \x01(\fR\x04data\x12!\n" +
	"\fchallenge_id\x18\f \x01(\tR\vchallengeId\x12\x1c\n" +
	"\tchallenge\x18\x06 \x01(\fR\tchallenge\x12\x13\n" +
	"\x05rp_id\x18\a \x01(\tR\x04rpId\x12X\n" +
	"\x13allowed_credentials\x18\b \x03(\v2'.se.mantra.api.public.AllowedCredentialR\x12allowedCredentials\x12+\n" +
	"\x11user_verification\x18\t \x01(\tR\x10userVerification\x12\x1c\n" +
	"\tmediation\x18\n" +
	" \x01(\tR\tmediation\x129\n" +
	"\n" +
	"expires_at\x18\v \x01(\v2\x1a.google.protobuf.TimestampR\texpiresAt\x12:\n" +
	"\blocation\x18\r \x01(\v2\x1e.se.mantra.api.common.LocationR\blocation\x129\n" +
	"\n" +
	"created_at\x18\x0e \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x127\n" +
	"\tsigned_at\x18\x0f \x01(\v2\x1a.google.protobuf.TimestampR\bsignedAt\"\x82\x03\n" +
	"\vSignRequest\x12!\n" +
	"\fchallenge_id\x18\x01 \x01(\tR\vchallengeId\x129\n" +
	"\x18authenticator_attachment\x18\x02 \x01(\tR\x17authenticatorAttachment\x12\x0e\n" +
	"\x02id\x18\x03 \x01(\tR\x02id\x12\x14\n" +
	"\x05rawId\x18\x04 \x01(\fR\x05rawId\x12-\n" +
	"\x12authenticator_data\x18\x05 \x01(\fR\x11authenticatorData\x12(\n" +
	"\x10client_data_json\x18\x06 \x01(\fR\x0eclientDataJson\x12\x1c\n" +
	"\tsignature\x18\a \x01(\fR\tsignature\x12\x1f\n" +
	"\vuser_handle\x18\b \x01(\fR\n" +
	"userHandle\x12:\n" +
	"\blocation\x18\t \x01(\v2\x1e.se.mantra.api.common.LocationR\blocation\x12\x1b\n" +
	"\tdevice_id\x18\n" +
	" \x01(\tR\bdeviceId\"+\n" +
	"\fSignResponse\x12\x1b\n" +
	"\tdevice_id\x18\x01 \x01(\tR\bdeviceId2\x88\x02\n" +
	"\vAuthService\x12Y\n" +
	"\x03Get\x12).se.mantra.api.public.GetChallengeRequest\x1a'.se.mantra.api.public.ChallengeResponse\x12M\n" +
	"\x04Sign\x12!.se.mantra.api.public.SignRequest\x1a\".se.mantra.api.public.SignResponse\x12O\n" +
	"\x06Reject\x12!.se.mantra.api.public.SignRequest\x1a\".se.mantra.api.public.SignResponseB0Z.github.com/daedaluz/mantra-cli/lib/grpc/publicb\x06proto3"

var (
	file_public_auth_proto_rawDescOnce sync.Once
	file_public_auth_proto_rawDescData []byte
)

func file_public_auth_proto_rawDescGZIP() []byte {
	file_public_auth_proto_rawDescOnce.Do(func() {
		file_public_auth_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_public_auth_proto_rawDesc), len(file_public_auth_proto_rawDesc)))
	})
	return file_public_auth_proto_rawDescData
}

var file_public_auth_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_public_auth_proto_goTypes = []any{
	(*AllowedCredential)(nil),     // 0: se.mantra.api.public.AllowedCredential
	(*GetChallengeRequest)(nil),   // 1: se.mantra.api.public.GetChallengeRequest
	(*ChallengeResponse)(nil),     // 2: se.mantra.api.public.ChallengeResponse
	(*SignRequest)(nil),           // 3: se.mantra.api.public.SignRequest
	(*SignResponse)(nil),          // 4: se.mantra.api.public.SignResponse
	(*common.ClientMeta)(nil),     // 5: se.mantra.api.common.ClientMeta
	(*timestamppb.Timestamp)(nil), // 6: google.protobuf.Timestamp
	(*common.Location)(nil),       // 7: se.mantra.api.common.Location
}
var file_public_auth_proto_depIdxs = []int32{
	5,  // 0: se.mantra.api.public.ChallengeResponse.client:type_name -> se.mantra.api.common.ClientMeta
	0,  // 1: se.mantra.api.public.ChallengeResponse.allowed_credentials:type_name -> se.mantra.api.public.AllowedCredential
	6,  // 2: se.mantra.api.public.ChallengeResponse.expires_at:type_name -> google.protobuf.Timestamp
	7,  // 3: se.mantra.api.public.ChallengeResponse.location:type_name -> se.mantra.api.common.Location
	6,  // 4: se.mantra.api.public.ChallengeResponse.created_at:type_name -> google.protobuf.Timestamp
	6,  // 5: se.mantra.api.public.ChallengeResponse.signed_at:type_name -> google.protobuf.Timestamp
	7,  // 6: se.mantra.api.public.SignRequest.location:type_name -> se.mantra.api.common.Location
	1,  // 7: se.mantra.api.public.AuthService.Get:input_type -> se.mantra.api.public.GetChallengeRequest
	3,  // 8: se.mantra.api.public.AuthService.Sign:input_type -> se.mantra.api.public.SignRequest
	3,  // 9: se.mantra.api.public.AuthService.Reject:input_type -> se.mantra.api.public.SignRequest
	2,  // 10: se.mantra.api.public.AuthService.Get:output_type -> se.mantra.api.public.ChallengeResponse
	4,  // 11: se.mantra.api.public.AuthService.Sign:output_type -> se.mantra.api.public.SignResponse
	4,  // 12: se.mantra.api.public.AuthService.Reject:output_type -> se.mantra.api.public.SignResponse
	10, // [10:13] is the sub-list for method output_type
	7,  // [7:10] is the sub-list for method input_type
	7,  // [7:7] is the sub-list for extension type_name
	7,  // [7:7] is the sub-list for extension extendee
	0,  // [0:7] is the sub-list for field type_name
}

func init() { file_public_auth_proto_init() }
func file_public_auth_proto_init() {
	if File_public_auth_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_public_auth_proto_rawDesc), len(file_public_auth_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_public_auth_proto_goTypes,
		DependencyIndexes: file_public_auth_proto_depIdxs,
		MessageInfos:      file_public_auth_proto_msgTypes,
	}.Build()
	File_public_auth_proto = out.File
	file_public_auth_proto_goTypes = nil
	file_public_auth_proto_depIdxs = nil
}
