// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.7
// 	protoc        (unknown)
// source: public/register.proto

package public

import (
	common "github.com/daedaluz/mantra/lib/grpc/common"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	_ "google.golang.org/protobuf/types/known/emptypb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RegistrationChallenge struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	RpId             string                 `protobuf:"bytes,1,opt,name=rp_id,json=rpId,proto3" json:"rp_id,omitempty"`
	RpName           string                 `protobuf:"bytes,2,opt,name=rp_name,json=rpName,proto3" json:"rp_name,omitempty"`
	UserId           []byte                 `protobuf:"bytes,3,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	DisplayName      string                 `protobuf:"bytes,4,opt,name=display_name,json=displayName,proto3" json:"display_name,omitempty"`
	Challenge        []byte                 `protobuf:"bytes,5,opt,name=challenge,proto3" json:"challenge,omitempty"`
	Algorithms       []int64                `protobuf:"varint,6,rep,packed,name=algorithms,proto3" json:"algorithms,omitempty"`
	Attestation      string                 `protobuf:"bytes,7,opt,name=attestation,proto3" json:"attestation,omitempty"`
	ResidentKey      string                 `protobuf:"bytes,8,opt,name=resident_key,json=residentKey,proto3" json:"resident_key,omitempty"`
	RequireResident  bool                   `protobuf:"varint,9,opt,name=require_resident,json=requireResident,proto3" json:"require_resident,omitempty"`
	UserVerification string                 `protobuf:"bytes,10,opt,name=user_verification,json=userVerification,proto3" json:"user_verification,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *RegistrationChallenge) Reset() {
	*x = RegistrationChallenge{}
	mi := &file_public_register_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegistrationChallenge) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegistrationChallenge) ProtoMessage() {}

func (x *RegistrationChallenge) ProtoReflect() protoreflect.Message {
	mi := &file_public_register_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegistrationChallenge.ProtoReflect.Descriptor instead.
func (*RegistrationChallenge) Descriptor() ([]byte, []int) {
	return file_public_register_proto_rawDescGZIP(), []int{0}
}

func (x *RegistrationChallenge) GetRpId() string {
	if x != nil {
		return x.RpId
	}
	return ""
}

func (x *RegistrationChallenge) GetRpName() string {
	if x != nil {
		return x.RpName
	}
	return ""
}

func (x *RegistrationChallenge) GetUserId() []byte {
	if x != nil {
		return x.UserId
	}
	return nil
}

func (x *RegistrationChallenge) GetDisplayName() string {
	if x != nil {
		return x.DisplayName
	}
	return ""
}

func (x *RegistrationChallenge) GetChallenge() []byte {
	if x != nil {
		return x.Challenge
	}
	return nil
}

func (x *RegistrationChallenge) GetAlgorithms() []int64 {
	if x != nil {
		return x.Algorithms
	}
	return nil
}

func (x *RegistrationChallenge) GetAttestation() string {
	if x != nil {
		return x.Attestation
	}
	return ""
}

func (x *RegistrationChallenge) GetResidentKey() string {
	if x != nil {
		return x.ResidentKey
	}
	return ""
}

func (x *RegistrationChallenge) GetRequireResident() bool {
	if x != nil {
		return x.RequireResident
	}
	return false
}

func (x *RegistrationChallenge) GetUserVerification() string {
	if x != nil {
		return x.UserVerification
	}
	return ""
}

type GetChallenge struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         string                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetChallenge) Reset() {
	*x = GetChallenge{}
	mi := &file_public_register_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetChallenge) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetChallenge) ProtoMessage() {}

func (x *GetChallenge) ProtoReflect() protoreflect.Message {
	mi := &file_public_register_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetChallenge.ProtoReflect.Descriptor instead.
func (*GetChallenge) Descriptor() ([]byte, []int) {
	return file_public_register_proto_rawDescGZIP(), []int{1}
}

func (x *GetChallenge) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

type GetResponse struct {
	state       protoimpl.MessageState `protogen:"open.v1"`
	ChallengeId string                 `protobuf:"bytes,1,opt,name=challenge_id,json=challengeId,proto3" json:"challenge_id,omitempty"`
	ExpiresAt   *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
	CreatedAt   *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	Client      *common.ClientMeta     `protobuf:"bytes,4,opt,name=client,proto3" json:"client,omitempty"`
	Challenge   *RegistrationChallenge `protobuf:"bytes,5,opt,name=challenge,proto3" json:"challenge,omitempty"`
	// Location where the registration request was initiated.
	// Frontend can use this to request location from the user if required.
	Location      *common.Location `protobuf:"bytes,6,opt,name=location,proto3" json:"location,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetResponse) Reset() {
	*x = GetResponse{}
	mi := &file_public_register_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetResponse) ProtoMessage() {}

func (x *GetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_public_register_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetResponse.ProtoReflect.Descriptor instead.
func (*GetResponse) Descriptor() ([]byte, []int) {
	return file_public_register_proto_rawDescGZIP(), []int{2}
}

func (x *GetResponse) GetChallengeId() string {
	if x != nil {
		return x.ChallengeId
	}
	return ""
}

func (x *GetResponse) GetExpiresAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ExpiresAt
	}
	return nil
}

func (x *GetResponse) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *GetResponse) GetClient() *common.ClientMeta {
	if x != nil {
		return x.Client
	}
	return nil
}

func (x *GetResponse) GetChallenge() *RegistrationChallenge {
	if x != nil {
		return x.Challenge
	}
	return nil
}

func (x *GetResponse) GetLocation() *common.Location {
	if x != nil {
		return x.Location
	}
	return nil
}

type RegisterRequest struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	ChallengeId        string                 `protobuf:"bytes,1,opt,name=challenge_id,json=challengeId,proto3" json:"challenge_id,omitempty"`
	Id                 string                 `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	RawId              []byte                 `protobuf:"bytes,3,opt,name=rawId,proto3" json:"rawId,omitempty"`
	Type               string                 `protobuf:"bytes,5,opt,name=type,proto3" json:"type,omitempty"`
	ClientDataJson     []byte                 `protobuf:"bytes,6,opt,name=client_data_json,json=clientDataJson,proto3" json:"client_data_json,omitempty"`
	AttestationObject  []byte                 `protobuf:"bytes,7,opt,name=attestation_object,json=attestationObject,proto3" json:"attestation_object,omitempty"`
	Attachment         string                 `protobuf:"bytes,8,opt,name=attachment,proto3" json:"attachment,omitempty"`
	PublicKeyAlgorithm int64                  `protobuf:"varint,10,opt,name=public_key_algorithm,json=publicKeyAlgorithm,proto3" json:"public_key_algorithm,omitempty"`
	Transports         []string               `protobuf:"bytes,9,rep,name=transports,proto3" json:"transports,omitempty"`
	Location           *common.Location       `protobuf:"bytes,11,opt,name=location,proto3" json:"location,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *RegisterRequest) Reset() {
	*x = RegisterRequest{}
	mi := &file_public_register_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterRequest) ProtoMessage() {}

func (x *RegisterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_public_register_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterRequest.ProtoReflect.Descriptor instead.
func (*RegisterRequest) Descriptor() ([]byte, []int) {
	return file_public_register_proto_rawDescGZIP(), []int{3}
}

func (x *RegisterRequest) GetChallengeId() string {
	if x != nil {
		return x.ChallengeId
	}
	return ""
}

func (x *RegisterRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *RegisterRequest) GetRawId() []byte {
	if x != nil {
		return x.RawId
	}
	return nil
}

func (x *RegisterRequest) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *RegisterRequest) GetClientDataJson() []byte {
	if x != nil {
		return x.ClientDataJson
	}
	return nil
}

func (x *RegisterRequest) GetAttestationObject() []byte {
	if x != nil {
		return x.AttestationObject
	}
	return nil
}

func (x *RegisterRequest) GetAttachment() string {
	if x != nil {
		return x.Attachment
	}
	return ""
}

func (x *RegisterRequest) GetPublicKeyAlgorithm() int64 {
	if x != nil {
		return x.PublicKeyAlgorithm
	}
	return 0
}

func (x *RegisterRequest) GetTransports() []string {
	if x != nil {
		return x.Transports
	}
	return nil
}

func (x *RegisterRequest) GetLocation() *common.Location {
	if x != nil {
		return x.Location
	}
	return nil
}

type RegisterResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterResponse) Reset() {
	*x = RegisterResponse{}
	mi := &file_public_register_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterResponse) ProtoMessage() {}

func (x *RegisterResponse) ProtoReflect() protoreflect.Message {
	mi := &file_public_register_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterResponse.ProtoReflect.Descriptor instead.
func (*RegisterResponse) Descriptor() ([]byte, []int) {
	return file_public_register_proto_rawDescGZIP(), []int{4}
}

var File_public_register_proto protoreflect.FileDescriptor

const file_public_register_proto_rawDesc = "" +
	"\n" +
	"\x15public/register.proto\x12\x14se.mantra.api.public\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1bgoogle/protobuf/empty.proto\x1a\x13common/common.proto\"\xdc\x02\n" +
	"\x15RegistrationChallenge\x12\x13\n" +
	"\x05rp_id\x18\x01 \x01(\tR\x04rpId\x12\x17\n" +
	"\arp_name\x18\x02 \x01(\tR\x06rpName\x12\x17\n" +
	"\auser_id\x18\x03 \x01(\fR\x06userId\x12!\n" +
	"\fdisplay_name\x18\x04 \x01(\tR\vdisplayName\x12\x1c\n" +
	"\tchallenge\x18\x05 \x01(\fR\tchallenge\x12\x1e\n" +
	"\n" +
	"algorithms\x18\x06 \x03(\x03R\n" +
	"algorithms\x12 \n" +
	"\vattestation\x18\a \x01(\tR\vattestation\x12!\n" +
	"\fresident_key\x18\b \x01(\tR\vresidentKey\x12)\n" +
	"\x10require_resident\x18\t \x01(\bR\x0frequireResident\x12+\n" +
	"\x11user_verification\x18\n" +
	" \x01(\tR\x10userVerification\"$\n" +
	"\fGetChallenge\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token\"\xe7\x02\n" +
	"\vGetResponse\x12!\n" +
	"\fchallenge_id\x18\x01 \x01(\tR\vchallengeId\x129\n" +
	"\n" +
	"expires_at\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\texpiresAt\x129\n" +
	"\n" +
	"created_at\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x128\n" +
	"\x06client\x18\x04 \x01(\v2 .se.mantra.api.common.ClientMetaR\x06client\x12I\n" +
	"\tchallenge\x18\x05 \x01(\v2+.se.mantra.api.public.RegistrationChallengeR\tchallenge\x12:\n" +
	"\blocation\x18\x06 \x01(\v2\x1e.se.mantra.api.common.LocationR\blocation\"\xf5\x02\n" +
	"\x0fRegisterRequest\x12!\n" +
	"\fchallenge_id\x18\x01 \x01(\tR\vchallengeId\x12\x0e\n" +
	"\x02id\x18\x02 \x01(\tR\x02id\x12\x14\n" +
	"\x05rawId\x18\x03 \x01(\fR\x05rawId\x12\x12\n" +
	"\x04type\x18\x05 \x01(\tR\x04type\x12(\n" +
	"\x10client_data_json\x18\x06 \x01(\fR\x0eclientDataJson\x12-\n" +
	"\x12attestation_object\x18\a \x01(\fR\x11attestationObject\x12\x1e\n" +
	"\n" +
	"attachment\x18\b \x01(\tR\n" +
	"attachment\x120\n" +
	"\x14public_key_algorithm\x18\n" +
	" \x01(\x03R\x12publicKeyAlgorithm\x12\x1e\n" +
	"\n" +
	"transports\x18\t \x03(\tR\n" +
	"transports\x12:\n" +
	"\blocation\x18\v \x01(\v2\x1e.se.mantra.api.common.LocationR\blocation\"\x12\n" +
	"\x10RegisterResponse2\xba\x01\n" +
	"\x0fRegisterService\x12L\n" +
	"\x03Get\x12\".se.mantra.api.public.GetChallenge\x1a!.se.mantra.api.public.GetResponse\x12Y\n" +
	"\bRegister\x12%.se.mantra.api.public.RegisterRequest\x1a&.se.mantra.api.public.RegisterResponseB,Z*github.com/daedaluz/mantra/lib/grpc/publicb\x06proto3"

var (
	file_public_register_proto_rawDescOnce sync.Once
	file_public_register_proto_rawDescData []byte
)

func file_public_register_proto_rawDescGZIP() []byte {
	file_public_register_proto_rawDescOnce.Do(func() {
		file_public_register_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_public_register_proto_rawDesc), len(file_public_register_proto_rawDesc)))
	})
	return file_public_register_proto_rawDescData
}

var file_public_register_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_public_register_proto_goTypes = []any{
	(*RegistrationChallenge)(nil), // 0: se.mantra.api.public.RegistrationChallenge
	(*GetChallenge)(nil),          // 1: se.mantra.api.public.GetChallenge
	(*GetResponse)(nil),           // 2: se.mantra.api.public.GetResponse
	(*RegisterRequest)(nil),       // 3: se.mantra.api.public.RegisterRequest
	(*RegisterResponse)(nil),      // 4: se.mantra.api.public.RegisterResponse
	(*timestamppb.Timestamp)(nil), // 5: google.protobuf.Timestamp
	(*common.ClientMeta)(nil),     // 6: se.mantra.api.common.ClientMeta
	(*common.Location)(nil),       // 7: se.mantra.api.common.Location
}
var file_public_register_proto_depIdxs = []int32{
	5, // 0: se.mantra.api.public.GetResponse.expires_at:type_name -> google.protobuf.Timestamp
	5, // 1: se.mantra.api.public.GetResponse.created_at:type_name -> google.protobuf.Timestamp
	6, // 2: se.mantra.api.public.GetResponse.client:type_name -> se.mantra.api.common.ClientMeta
	0, // 3: se.mantra.api.public.GetResponse.challenge:type_name -> se.mantra.api.public.RegistrationChallenge
	7, // 4: se.mantra.api.public.GetResponse.location:type_name -> se.mantra.api.common.Location
	7, // 5: se.mantra.api.public.RegisterRequest.location:type_name -> se.mantra.api.common.Location
	1, // 6: se.mantra.api.public.RegisterService.Get:input_type -> se.mantra.api.public.GetChallenge
	3, // 7: se.mantra.api.public.RegisterService.Register:input_type -> se.mantra.api.public.RegisterRequest
	2, // 8: se.mantra.api.public.RegisterService.Get:output_type -> se.mantra.api.public.GetResponse
	4, // 9: se.mantra.api.public.RegisterService.Register:output_type -> se.mantra.api.public.RegisterResponse
	8, // [8:10] is the sub-list for method output_type
	6, // [6:8] is the sub-list for method input_type
	6, // [6:6] is the sub-list for extension type_name
	6, // [6:6] is the sub-list for extension extendee
	0, // [0:6] is the sub-list for field type_name
}

func init() { file_public_register_proto_init() }
func file_public_register_proto_init() {
	if File_public_register_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_public_register_proto_rawDesc), len(file_public_register_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_public_register_proto_goTypes,
		DependencyIndexes: file_public_register_proto_depIdxs,
		MessageInfos:      file_public_register_proto_msgTypes,
	}.Build()
	File_public_register_proto = out.File
	file_public_register_proto_goTypes = nil
	file_public_register_proto_depIdxs = nil
}
