// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: service/domain_admin.proto

package admin

import (
	common "github.com/daedaluz/mantra-cli/lib/grpc/common"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetUserRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserRequest) Reset() {
	*x = GetUserRequest{}
	mi := &file_service_domain_admin_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserRequest) ProtoMessage() {}

func (x *GetUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_service_domain_admin_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserRequest.ProtoReflect.Descriptor instead.
func (*GetUserRequest) Descriptor() ([]byte, []int) {
	return file_service_domain_admin_proto_rawDescGZIP(), []int{0}
}

func (x *GetUserRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type GetUserResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Domain        string                 `protobuf:"bytes,1,opt,name=domain,proto3" json:"domain,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	Keys          []*common.Key          `protobuf:"bytes,4,rep,name=keys,proto3" json:"keys,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserResponse) Reset() {
	*x = GetUserResponse{}
	mi := &file_service_domain_admin_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserResponse) ProtoMessage() {}

func (x *GetUserResponse) ProtoReflect() protoreflect.Message {
	mi := &file_service_domain_admin_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserResponse.ProtoReflect.Descriptor instead.
func (*GetUserResponse) Descriptor() ([]byte, []int) {
	return file_service_domain_admin_proto_rawDescGZIP(), []int{1}
}

func (x *GetUserResponse) GetDomain() string {
	if x != nil {
		return x.Domain
	}
	return ""
}

func (x *GetUserResponse) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *GetUserResponse) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *GetUserResponse) GetKeys() []*common.Key {
	if x != nil {
		return x.Keys
	}
	return nil
}

type CreateUserRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Timeout       int64                  `protobuf:"varint,4,opt,name=timeout,proto3" json:"timeout,omitempty"`
	ReturnUrl     string                 `protobuf:"bytes,5,opt,name=return_url,json=returnUrl,proto3" json:"return_url,omitempty"`
	Location      *common.Location       `protobuf:"bytes,6,opt,name=location,proto3" json:"location,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateUserRequest) Reset() {
	*x = CreateUserRequest{}
	mi := &file_service_domain_admin_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateUserRequest) ProtoMessage() {}

func (x *CreateUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_service_domain_admin_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateUserRequest.ProtoReflect.Descriptor instead.
func (*CreateUserRequest) Descriptor() ([]byte, []int) {
	return file_service_domain_admin_proto_rawDescGZIP(), []int{2}
}

func (x *CreateUserRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *CreateUserRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateUserRequest) GetTimeout() int64 {
	if x != nil {
		return x.Timeout
	}
	return 0
}

func (x *CreateUserRequest) GetReturnUrl() string {
	if x != nil {
		return x.ReturnUrl
	}
	return ""
}

func (x *CreateUserRequest) GetLocation() *common.Location {
	if x != nil {
		return x.Location
	}
	return nil
}

type AddKeyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Timeout       int64                  `protobuf:"varint,4,opt,name=timeout,proto3" json:"timeout,omitempty"`
	ReturnUrl     string                 `protobuf:"bytes,5,opt,name=return_url,json=returnUrl,proto3" json:"return_url,omitempty"`
	Location      *common.Location       `protobuf:"bytes,6,opt,name=location,proto3" json:"location,omitempty"`
	Pending       bool                   `protobuf:"varint,7,opt,name=pending,proto3" json:"pending,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddKeyRequest) Reset() {
	*x = AddKeyRequest{}
	mi := &file_service_domain_admin_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddKeyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddKeyRequest) ProtoMessage() {}

func (x *AddKeyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_service_domain_admin_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddKeyRequest.ProtoReflect.Descriptor instead.
func (*AddKeyRequest) Descriptor() ([]byte, []int) {
	return file_service_domain_admin_proto_rawDescGZIP(), []int{3}
}

func (x *AddKeyRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *AddKeyRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *AddKeyRequest) GetTimeout() int64 {
	if x != nil {
		return x.Timeout
	}
	return 0
}

func (x *AddKeyRequest) GetReturnUrl() string {
	if x != nil {
		return x.ReturnUrl
	}
	return ""
}

func (x *AddKeyRequest) GetLocation() *common.Location {
	if x != nil {
		return x.Location
	}
	return nil
}

func (x *AddKeyRequest) GetPending() bool {
	if x != nil {
		return x.Pending
	}
	return false
}

type RevokeKeyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	KeyId         []byte                 `protobuf:"bytes,3,opt,name=key_id,json=keyId,proto3" json:"key_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RevokeKeyRequest) Reset() {
	*x = RevokeKeyRequest{}
	mi := &file_service_domain_admin_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RevokeKeyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RevokeKeyRequest) ProtoMessage() {}

func (x *RevokeKeyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_service_domain_admin_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RevokeKeyRequest.ProtoReflect.Descriptor instead.
func (*RevokeKeyRequest) Descriptor() ([]byte, []int) {
	return file_service_domain_admin_proto_rawDescGZIP(), []int{4}
}

func (x *RevokeKeyRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *RevokeKeyRequest) GetKeyId() []byte {
	if x != nil {
		return x.KeyId
	}
	return nil
}

type RevokeKeyResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RevokeKeyResponse) Reset() {
	*x = RevokeKeyResponse{}
	mi := &file_service_domain_admin_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RevokeKeyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RevokeKeyResponse) ProtoMessage() {}

func (x *RevokeKeyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_service_domain_admin_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RevokeKeyResponse.ProtoReflect.Descriptor instead.
func (*RevokeKeyResponse) Descriptor() ([]byte, []int) {
	return file_service_domain_admin_proto_rawDescGZIP(), []int{5}
}

func (x *RevokeKeyResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type ActivateKeyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	KeyId         []byte                 `protobuf:"bytes,2,opt,name=key_id,json=keyId,proto3" json:"key_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ActivateKeyRequest) Reset() {
	*x = ActivateKeyRequest{}
	mi := &file_service_domain_admin_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ActivateKeyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ActivateKeyRequest) ProtoMessage() {}

func (x *ActivateKeyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_service_domain_admin_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ActivateKeyRequest.ProtoReflect.Descriptor instead.
func (*ActivateKeyRequest) Descriptor() ([]byte, []int) {
	return file_service_domain_admin_proto_rawDescGZIP(), []int{6}
}

func (x *ActivateKeyRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *ActivateKeyRequest) GetKeyId() []byte {
	if x != nil {
		return x.KeyId
	}
	return nil
}

type ActivateKeyResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ActivateKeyResponse) Reset() {
	*x = ActivateKeyResponse{}
	mi := &file_service_domain_admin_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ActivateKeyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ActivateKeyResponse) ProtoMessage() {}

func (x *ActivateKeyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_service_domain_admin_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ActivateKeyResponse.ProtoReflect.Descriptor instead.
func (*ActivateKeyResponse) Descriptor() ([]byte, []int) {
	return file_service_domain_admin_proto_rawDescGZIP(), []int{7}
}

func (x *ActivateKeyResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type DeleteUserRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteUserRequest) Reset() {
	*x = DeleteUserRequest{}
	mi := &file_service_domain_admin_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteUserRequest) ProtoMessage() {}

func (x *DeleteUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_service_domain_admin_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteUserRequest.ProtoReflect.Descriptor instead.
func (*DeleteUserRequest) Descriptor() ([]byte, []int) {
	return file_service_domain_admin_proto_rawDescGZIP(), []int{8}
}

func (x *DeleteUserRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type CreateClientRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	Icon          string                 `protobuf:"bytes,3,opt,name=icon,proto3" json:"icon,omitempty"`
	Admin         bool                   `protobuf:"varint,4,opt,name=admin,proto3" json:"admin,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateClientRequest) Reset() {
	*x = CreateClientRequest{}
	mi := &file_service_domain_admin_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateClientRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateClientRequest) ProtoMessage() {}

func (x *CreateClientRequest) ProtoReflect() protoreflect.Message {
	mi := &file_service_domain_admin_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateClientRequest.ProtoReflect.Descriptor instead.
func (*CreateClientRequest) Descriptor() ([]byte, []int) {
	return file_service_domain_admin_proto_rawDescGZIP(), []int{9}
}

func (x *CreateClientRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateClientRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *CreateClientRequest) GetIcon() string {
	if x != nil {
		return x.Icon
	}
	return ""
}

func (x *CreateClientRequest) GetAdmin() bool {
	if x != nil {
		return x.Admin
	}
	return false
}

type CreateClientResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ClientId      string                 `protobuf:"bytes,1,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	ClientSecret  string                 `protobuf:"bytes,2,opt,name=client_secret,json=clientSecret,proto3" json:"client_secret,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	Icon          string                 `protobuf:"bytes,5,opt,name=icon,proto3" json:"icon,omitempty"`
	Admin         bool                   `protobuf:"varint,6,opt,name=admin,proto3" json:"admin,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateClientResponse) Reset() {
	*x = CreateClientResponse{}
	mi := &file_service_domain_admin_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateClientResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateClientResponse) ProtoMessage() {}

func (x *CreateClientResponse) ProtoReflect() protoreflect.Message {
	mi := &file_service_domain_admin_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateClientResponse.ProtoReflect.Descriptor instead.
func (*CreateClientResponse) Descriptor() ([]byte, []int) {
	return file_service_domain_admin_proto_rawDescGZIP(), []int{10}
}

func (x *CreateClientResponse) GetClientId() string {
	if x != nil {
		return x.ClientId
	}
	return ""
}

func (x *CreateClientResponse) GetClientSecret() string {
	if x != nil {
		return x.ClientSecret
	}
	return ""
}

func (x *CreateClientResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateClientResponse) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *CreateClientResponse) GetIcon() string {
	if x != nil {
		return x.Icon
	}
	return ""
}

func (x *CreateClientResponse) GetAdmin() bool {
	if x != nil {
		return x.Admin
	}
	return false
}

type DeleteClientRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ClientId      string                 `protobuf:"bytes,1,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteClientRequest) Reset() {
	*x = DeleteClientRequest{}
	mi := &file_service_domain_admin_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteClientRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteClientRequest) ProtoMessage() {}

func (x *DeleteClientRequest) ProtoReflect() protoreflect.Message {
	mi := &file_service_domain_admin_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteClientRequest.ProtoReflect.Descriptor instead.
func (*DeleteClientRequest) Descriptor() ([]byte, []int) {
	return file_service_domain_admin_proto_rawDescGZIP(), []int{11}
}

func (x *DeleteClientRequest) GetClientId() string {
	if x != nil {
		return x.ClientId
	}
	return ""
}

type CollectRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	ChallengeId     string                 `protobuf:"bytes,1,opt,name=challenge_id,json=challengeId,proto3" json:"challenge_id,omitempty"`
	ChallengeSecret string                 `protobuf:"bytes,2,opt,name=challenge_secret,json=challengeSecret,proto3" json:"challenge_secret,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *CollectRequest) Reset() {
	*x = CollectRequest{}
	mi := &file_service_domain_admin_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CollectRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CollectRequest) ProtoMessage() {}

func (x *CollectRequest) ProtoReflect() protoreflect.Message {
	mi := &file_service_domain_admin_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CollectRequest.ProtoReflect.Descriptor instead.
func (*CollectRequest) Descriptor() ([]byte, []int) {
	return file_service_domain_admin_proto_rawDescGZIP(), []int{12}
}

func (x *CollectRequest) GetChallengeId() string {
	if x != nil {
		return x.ChallengeId
	}
	return ""
}

func (x *CollectRequest) GetChallengeSecret() string {
	if x != nil {
		return x.ChallengeSecret
	}
	return ""
}

type CollectResponse struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Status            common.Status          `protobuf:"varint,1,opt,name=status,proto3,enum=se.mantra.api.common.Status" json:"status,omitempty"`
	UserId            string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Challenge         []byte                 `protobuf:"bytes,3,opt,name=challenge,proto3" json:"challenge,omitempty"`
	KeyId             []byte                 `protobuf:"bytes,4,opt,name=key_id,json=keyId,proto3" json:"key_id,omitempty"`
	Algorithm         int64                  `protobuf:"varint,5,opt,name=algorithm,proto3" json:"algorithm,omitempty"`
	PublicKey         []byte                 `protobuf:"bytes,6,opt,name=public_key,json=publicKey,proto3" json:"public_key,omitempty"`
	Aaguid            []byte                 `protobuf:"bytes,7,opt,name=aaguid,proto3" json:"aaguid,omitempty"`
	AttestationType   string                 `protobuf:"bytes,8,opt,name=attestation_type,json=attestationType,proto3" json:"attestation_type,omitempty"`
	ClientDataJson    []byte                 `protobuf:"bytes,9,opt,name=client_data_json,json=clientDataJson,proto3" json:"client_data_json,omitempty"`
	AttestationObject []byte                 `protobuf:"bytes,10,opt,name=attestation_object,json=attestationObject,proto3" json:"attestation_object,omitempty"`
	CreatedAt         *timestamppb.Timestamp `protobuf:"bytes,11,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	Location          *common.Location       `protobuf:"bytes,12,opt,name=location,proto3" json:"location,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *CollectResponse) Reset() {
	*x = CollectResponse{}
	mi := &file_service_domain_admin_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CollectResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CollectResponse) ProtoMessage() {}

func (x *CollectResponse) ProtoReflect() protoreflect.Message {
	mi := &file_service_domain_admin_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CollectResponse.ProtoReflect.Descriptor instead.
func (*CollectResponse) Descriptor() ([]byte, []int) {
	return file_service_domain_admin_proto_rawDescGZIP(), []int{13}
}

func (x *CollectResponse) GetStatus() common.Status {
	if x != nil {
		return x.Status
	}
	return common.Status(0)
}

func (x *CollectResponse) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *CollectResponse) GetChallenge() []byte {
	if x != nil {
		return x.Challenge
	}
	return nil
}

func (x *CollectResponse) GetKeyId() []byte {
	if x != nil {
		return x.KeyId
	}
	return nil
}

func (x *CollectResponse) GetAlgorithm() int64 {
	if x != nil {
		return x.Algorithm
	}
	return 0
}

func (x *CollectResponse) GetPublicKey() []byte {
	if x != nil {
		return x.PublicKey
	}
	return nil
}

func (x *CollectResponse) GetAaguid() []byte {
	if x != nil {
		return x.Aaguid
	}
	return nil
}

func (x *CollectResponse) GetAttestationType() string {
	if x != nil {
		return x.AttestationType
	}
	return ""
}

func (x *CollectResponse) GetClientDataJson() []byte {
	if x != nil {
		return x.ClientDataJson
	}
	return nil
}

func (x *CollectResponse) GetAttestationObject() []byte {
	if x != nil {
		return x.AttestationObject
	}
	return nil
}

func (x *CollectResponse) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *CollectResponse) GetLocation() *common.Location {
	if x != nil {
		return x.Location
	}
	return nil
}

type ListUsersResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Users         []string               `protobuf:"bytes,1,rep,name=users,proto3" json:"users,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListUsersResponse) Reset() {
	*x = ListUsersResponse{}
	mi := &file_service_domain_admin_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListUsersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListUsersResponse) ProtoMessage() {}

func (x *ListUsersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_service_domain_admin_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListUsersResponse.ProtoReflect.Descriptor instead.
func (*ListUsersResponse) Descriptor() ([]byte, []int) {
	return file_service_domain_admin_proto_rawDescGZIP(), []int{14}
}

func (x *ListUsersResponse) GetUsers() []string {
	if x != nil {
		return x.Users
	}
	return nil
}

type ListClientsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AdminOnly     bool                   `protobuf:"varint,1,opt,name=admin_only,json=adminOnly,proto3" json:"admin_only,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListClientsRequest) Reset() {
	*x = ListClientsRequest{}
	mi := &file_service_domain_admin_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListClientsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListClientsRequest) ProtoMessage() {}

func (x *ListClientsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_service_domain_admin_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListClientsRequest.ProtoReflect.Descriptor instead.
func (*ListClientsRequest) Descriptor() ([]byte, []int) {
	return file_service_domain_admin_proto_rawDescGZIP(), []int{15}
}

func (x *ListClientsRequest) GetAdminOnly() bool {
	if x != nil {
		return x.AdminOnly
	}
	return false
}

type ListClientsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Clients       []*common.ClientMeta   `protobuf:"bytes,1,rep,name=clients,proto3" json:"clients,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListClientsResponse) Reset() {
	*x = ListClientsResponse{}
	mi := &file_service_domain_admin_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListClientsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListClientsResponse) ProtoMessage() {}

func (x *ListClientsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_service_domain_admin_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListClientsResponse.ProtoReflect.Descriptor instead.
func (*ListClientsResponse) Descriptor() ([]byte, []int) {
	return file_service_domain_admin_proto_rawDescGZIP(), []int{16}
}

func (x *ListClientsResponse) GetClients() []*common.ClientMeta {
	if x != nil {
		return x.Clients
	}
	return nil
}

type UpdateDomainDetailsRequest struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	Name                 string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Description          string                 `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	Algorithms           []int64                `protobuf:"varint,3,rep,packed,name=algorithms,proto3" json:"algorithms,omitempty"`
	RegistrationPath     string                 `protobuf:"bytes,4,opt,name=registration_path,json=registrationPath,proto3" json:"registration_path,omitempty"`
	SignPath             string                 `protobuf:"bytes,5,opt,name=sign_path,json=signPath,proto3" json:"sign_path,omitempty"`
	RequireDeviceBinding bool                   `protobuf:"varint,6,opt,name=require_device_binding,json=requireDeviceBinding,proto3" json:"require_device_binding,omitempty"`
	TokenMaxAge          int32                  `protobuf:"varint,7,opt,name=token_max_age,json=tokenMaxAge,proto3" json:"token_max_age,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *UpdateDomainDetailsRequest) Reset() {
	*x = UpdateDomainDetailsRequest{}
	mi := &file_service_domain_admin_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateDomainDetailsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateDomainDetailsRequest) ProtoMessage() {}

func (x *UpdateDomainDetailsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_service_domain_admin_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateDomainDetailsRequest.ProtoReflect.Descriptor instead.
func (*UpdateDomainDetailsRequest) Descriptor() ([]byte, []int) {
	return file_service_domain_admin_proto_rawDescGZIP(), []int{17}
}

func (x *UpdateDomainDetailsRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UpdateDomainDetailsRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *UpdateDomainDetailsRequest) GetAlgorithms() []int64 {
	if x != nil {
		return x.Algorithms
	}
	return nil
}

func (x *UpdateDomainDetailsRequest) GetRegistrationPath() string {
	if x != nil {
		return x.RegistrationPath
	}
	return ""
}

func (x *UpdateDomainDetailsRequest) GetSignPath() string {
	if x != nil {
		return x.SignPath
	}
	return ""
}

func (x *UpdateDomainDetailsRequest) GetRequireDeviceBinding() bool {
	if x != nil {
		return x.RequireDeviceBinding
	}
	return false
}

func (x *UpdateDomainDetailsRequest) GetTokenMaxAge() int32 {
	if x != nil {
		return x.TokenMaxAge
	}
	return 0
}

type DomainDetails struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	Domain               string                 `protobuf:"bytes,1,opt,name=domain,proto3" json:"domain,omitempty"`
	Name                 string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description          string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Algorithms           []int64                `protobuf:"varint,4,rep,packed,name=algorithms,proto3" json:"algorithms,omitempty"`
	CreatedAt            *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	RegistrationPath     string                 `protobuf:"bytes,6,opt,name=registration_path,json=registrationPath,proto3" json:"registration_path,omitempty"`
	SignPath             string                 `protobuf:"bytes,7,opt,name=sign_path,json=signPath,proto3" json:"sign_path,omitempty"`
	RequireDeviceBinding bool                   `protobuf:"varint,8,opt,name=require_device_binding,json=requireDeviceBinding,proto3" json:"require_device_binding,omitempty"`
	TokenMaxAge          int32                  `protobuf:"varint,9,opt,name=token_max_age,json=tokenMaxAge,proto3" json:"token_max_age,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *DomainDetails) Reset() {
	*x = DomainDetails{}
	mi := &file_service_domain_admin_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DomainDetails) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DomainDetails) ProtoMessage() {}

func (x *DomainDetails) ProtoReflect() protoreflect.Message {
	mi := &file_service_domain_admin_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DomainDetails.ProtoReflect.Descriptor instead.
func (*DomainDetails) Descriptor() ([]byte, []int) {
	return file_service_domain_admin_proto_rawDescGZIP(), []int{18}
}

func (x *DomainDetails) GetDomain() string {
	if x != nil {
		return x.Domain
	}
	return ""
}

func (x *DomainDetails) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *DomainDetails) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *DomainDetails) GetAlgorithms() []int64 {
	if x != nil {
		return x.Algorithms
	}
	return nil
}

func (x *DomainDetails) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *DomainDetails) GetRegistrationPath() string {
	if x != nil {
		return x.RegistrationPath
	}
	return ""
}

func (x *DomainDetails) GetSignPath() string {
	if x != nil {
		return x.SignPath
	}
	return ""
}

func (x *DomainDetails) GetRequireDeviceBinding() bool {
	if x != nil {
		return x.RequireDeviceBinding
	}
	return false
}

func (x *DomainDetails) GetTokenMaxAge() int32 {
	if x != nil {
		return x.TokenMaxAge
	}
	return 0
}

var File_service_domain_admin_proto protoreflect.FileDescriptor

const file_service_domain_admin_proto_rawDesc = "" +
	"\n" +
	"\x1aservice/domain_admin.proto\x12\x13se.mantra.api.admin\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1bgoogle/protobuf/empty.proto\x1a\x13common/common.proto\")\n" +
	"\x0eGetUserRequest\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\"\xac\x01\n" +
	"\x0fGetUserResponse\x12\x16\n" +
	"\x06domain\x18\x01 \x01(\tR\x06domain\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x129\n" +
	"\n" +
	"created_at\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x12-\n" +
	"\x04keys\x18\x04 \x03(\v2\x19.se.mantra.api.common.KeyR\x04keys\"\xb5\x01\n" +
	"\x11CreateUserRequest\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12\x18\n" +
	"\atimeout\x18\x04 \x01(\x03R\atimeout\x12\x1d\n" +
	"\n" +
	"return_url\x18\x05 \x01(\tR\treturnUrl\x12:\n" +
	"\blocation\x18\x06 \x01(\v2\x1e.se.mantra.api.common.LocationR\blocation\"\xcb\x01\n" +
	"\rAddKeyRequest\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12\x18\n" +
	"\atimeout\x18\x04 \x01(\x03R\atimeout\x12\x1d\n" +
	"\n" +
	"return_url\x18\x05 \x01(\tR\treturnUrl\x12:\n" +
	"\blocation\x18\x06 \x01(\v2\x1e.se.mantra.api.common.LocationR\blocation\x12\x18\n" +
	"\apending\x18\a \x01(\bR\apending\"B\n" +
	"\x10RevokeKeyRequest\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x15\n" +
	"\x06key_id\x18\x03 \x01(\fR\x05keyId\"-\n" +
	"\x11RevokeKeyResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"D\n" +
	"\x12ActivateKeyRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x15\n" +
	"\x06key_id\x18\x02 \x01(\fR\x05keyId\"/\n" +
	"\x13ActivateKeyResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\",\n" +
	"\x11DeleteUserRequest\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\"u\n" +
	"\x13CreateClientRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\x12\x12\n" +
	"\x04icon\x18\x03 \x01(\tR\x04icon\x12\x14\n" +
	"\x05admin\x18\x04 \x01(\bR\x05admin\"\xb8\x01\n" +
	"\x14CreateClientResponse\x12\x1b\n" +
	"\tclient_id\x18\x01 \x01(\tR\bclientId\x12#\n" +
	"\rclient_secret\x18\x02 \x01(\tR\fclientSecret\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x04 \x01(\tR\vdescription\x12\x12\n" +
	"\x04icon\x18\x05 \x01(\tR\x04icon\x12\x14\n" +
	"\x05admin\x18\x06 \x01(\bR\x05admin\"2\n" +
	"\x13DeleteClientRequest\x12\x1b\n" +
	"\tclient_id\x18\x01 \x01(\tR\bclientId\"^\n" +
	"\x0eCollectRequest\x12!\n" +
	"\fchallenge_id\x18\x01 \x01(\tR\vchallengeId\x12)\n" +
	"\x10challenge_secret\x18\x02 \x01(\tR\x0fchallengeSecret\"\xe5\x03\n" +
	"\x0fCollectResponse\x124\n" +
	"\x06status\x18\x01 \x01(\x0e2\x1c.se.mantra.api.common.StatusR\x06status\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x1c\n" +
	"\tchallenge\x18\x03 \x01(\fR\tchallenge\x12\x15\n" +
	"\x06key_id\x18\x04 \x01(\fR\x05keyId\x12\x1c\n" +
	"\talgorithm\x18\x05 \x01(\x03R\talgorithm\x12\x1d\n" +
	"\n" +
	"public_key\x18\x06 \x01(\fR\tpublicKey\x12\x16\n" +
	"\x06aaguid\x18\a \x01(\fR\x06aaguid\x12)\n" +
	"\x10attestation_type\x18\b \x01(\tR\x0fattestationType\x12(\n" +
	"\x10client_data_json\x18\t \x01(\fR\x0eclientDataJson\x12-\n" +
	"\x12attestation_object\x18\n" +
	" \x01(\fR\x11attestationObject\x129\n" +
	"\n" +
	"created_at\x18\v \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x12:\n" +
	"\blocation\x18\f \x01(\v2\x1e.se.mantra.api.common.LocationR\blocation\")\n" +
	"\x11ListUsersResponse\x12\x14\n" +
	"\x05users\x18\x01 \x03(\tR\x05users\"3\n" +
	"\x12ListClientsRequest\x12\x1d\n" +
	"\n" +
	"admin_only\x18\x01 \x01(\bR\tadminOnly\"Q\n" +
	"\x13ListClientsResponse\x12:\n" +
	"\aclients\x18\x01 \x03(\v2 .se.mantra.api.common.ClientMetaR\aclients\"\x96\x02\n" +
	"\x1aUpdateDomainDetailsRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\x12\x1e\n" +
	"\n" +
	"algorithms\x18\x03 \x03(\x03R\n" +
	"algorithms\x12+\n" +
	"\x11registration_path\x18\x04 \x01(\tR\x10registrationPath\x12\x1b\n" +
	"\tsign_path\x18\x05 \x01(\tR\bsignPath\x124\n" +
	"\x16require_device_binding\x18\x06 \x01(\bR\x14requireDeviceBinding\x12\"\n" +
	"\rtoken_max_age\x18\a \x01(\x05R\vtokenMaxAge\"\xdc\x02\n" +
	"\rDomainDetails\x12\x16\n" +
	"\x06domain\x18\x01 \x01(\tR\x06domain\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x1e\n" +
	"\n" +
	"algorithms\x18\x04 \x03(\x03R\n" +
	"algorithms\x129\n" +
	"\n" +
	"created_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x12+\n" +
	"\x11registration_path\x18\x06 \x01(\tR\x10registrationPath\x12\x1b\n" +
	"\tsign_path\x18\a \x01(\tR\bsignPath\x124\n" +
	"\x16require_device_binding\x18\b \x01(\bR\x14requireDeviceBinding\x12\"\n" +
	"\rtoken_max_age\x18\t \x01(\x05R\vtokenMaxAge2\x9f\t\n" +
	"\x12DomainAdminService\x12]\n" +
	"\n" +
	"CreateUser\x12&.se.mantra.api.admin.CreateUserRequest\x1a'.se.mantra.api.common.ChallengeResponse\x12T\n" +
	"\aGetUser\x12#.se.mantra.api.admin.GetUserRequest\x1a$.se.mantra.api.admin.GetUserResponse\x12K\n" +
	"\tListUsers\x12\x16.google.protobuf.Empty\x1a&.se.mantra.api.admin.ListUsersResponse\x12L\n" +
	"\n" +
	"DeleteUser\x12&.se.mantra.api.admin.DeleteUserRequest\x1a\x16.google.protobuf.Empty\x12U\n" +
	"\x06AddKey\x12\".se.mantra.api.admin.AddKeyRequest\x1a'.se.mantra.api.common.ChallengeResponse\x12Z\n" +
	"\tRevokeKey\x12%.se.mantra.api.admin.RevokeKeyRequest\x1a&.se.mantra.api.admin.RevokeKeyResponse\x12`\n" +
	"\vActivateKey\x12'.se.mantra.api.admin.ActivateKeyRequest\x1a(.se.mantra.api.admin.ActivateKeyResponse\x12]\n" +
	"\x10CollectChallenge\x12#.se.mantra.api.admin.CollectRequest\x1a$.se.mantra.api.admin.CollectResponse\x12c\n" +
	"\fCreateClient\x12(.se.mantra.api.admin.CreateClientRequest\x1a).se.mantra.api.admin.CreateClientResponse\x12P\n" +
	"\fDeleteClient\x12(.se.mantra.api.admin.DeleteClientRequest\x1a\x16.google.protobuf.Empty\x12`\n" +
	"\vListClients\x12'.se.mantra.api.admin.ListClientsRequest\x1a(.se.mantra.api.admin.ListClientsResponse\x12c\n" +
	"\fUpdateDomain\x12/.se.mantra.api.admin.UpdateDomainDetailsRequest\x1a\".se.mantra.api.admin.DomainDetails\x12G\n" +
	"\tGetDomain\x12\x16.google.protobuf.Empty\x1a\".se.mantra.api.admin.DomainDetailsB/Z-github.com/daedaluz/mantra-cli/lib/grpc/adminb\x06proto3"

var (
	file_service_domain_admin_proto_rawDescOnce sync.Once
	file_service_domain_admin_proto_rawDescData []byte
)

func file_service_domain_admin_proto_rawDescGZIP() []byte {
	file_service_domain_admin_proto_rawDescOnce.Do(func() {
		file_service_domain_admin_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_service_domain_admin_proto_rawDesc), len(file_service_domain_admin_proto_rawDesc)))
	})
	return file_service_domain_admin_proto_rawDescData
}

var file_service_domain_admin_proto_msgTypes = make([]protoimpl.MessageInfo, 19)
var file_service_domain_admin_proto_goTypes = []any{
	(*GetUserRequest)(nil),             // 0: se.mantra.api.admin.GetUserRequest
	(*GetUserResponse)(nil),            // 1: se.mantra.api.admin.GetUserResponse
	(*CreateUserRequest)(nil),          // 2: se.mantra.api.admin.CreateUserRequest
	(*AddKeyRequest)(nil),              // 3: se.mantra.api.admin.AddKeyRequest
	(*RevokeKeyRequest)(nil),           // 4: se.mantra.api.admin.RevokeKeyRequest
	(*RevokeKeyResponse)(nil),          // 5: se.mantra.api.admin.RevokeKeyResponse
	(*ActivateKeyRequest)(nil),         // 6: se.mantra.api.admin.ActivateKeyRequest
	(*ActivateKeyResponse)(nil),        // 7: se.mantra.api.admin.ActivateKeyResponse
	(*DeleteUserRequest)(nil),          // 8: se.mantra.api.admin.DeleteUserRequest
	(*CreateClientRequest)(nil),        // 9: se.mantra.api.admin.CreateClientRequest
	(*CreateClientResponse)(nil),       // 10: se.mantra.api.admin.CreateClientResponse
	(*DeleteClientRequest)(nil),        // 11: se.mantra.api.admin.DeleteClientRequest
	(*CollectRequest)(nil),             // 12: se.mantra.api.admin.CollectRequest
	(*CollectResponse)(nil),            // 13: se.mantra.api.admin.CollectResponse
	(*ListUsersResponse)(nil),          // 14: se.mantra.api.admin.ListUsersResponse
	(*ListClientsRequest)(nil),         // 15: se.mantra.api.admin.ListClientsRequest
	(*ListClientsResponse)(nil),        // 16: se.mantra.api.admin.ListClientsResponse
	(*UpdateDomainDetailsRequest)(nil), // 17: se.mantra.api.admin.UpdateDomainDetailsRequest
	(*DomainDetails)(nil),              // 18: se.mantra.api.admin.DomainDetails
	(*timestamppb.Timestamp)(nil),      // 19: google.protobuf.Timestamp
	(*common.Key)(nil),                 // 20: se.mantra.api.common.Key
	(*common.Location)(nil),            // 21: se.mantra.api.common.Location
	(common.Status)(0),                 // 22: se.mantra.api.common.Status
	(*common.ClientMeta)(nil),          // 23: se.mantra.api.common.ClientMeta
	(*emptypb.Empty)(nil),              // 24: google.protobuf.Empty
	(*common.ChallengeResponse)(nil),   // 25: se.mantra.api.common.ChallengeResponse
}
var file_service_domain_admin_proto_depIdxs = []int32{
	19, // 0: se.mantra.api.admin.GetUserResponse.created_at:type_name -> google.protobuf.Timestamp
	20, // 1: se.mantra.api.admin.GetUserResponse.keys:type_name -> se.mantra.api.common.Key
	21, // 2: se.mantra.api.admin.CreateUserRequest.location:type_name -> se.mantra.api.common.Location
	21, // 3: se.mantra.api.admin.AddKeyRequest.location:type_name -> se.mantra.api.common.Location
	22, // 4: se.mantra.api.admin.CollectResponse.status:type_name -> se.mantra.api.common.Status
	19, // 5: se.mantra.api.admin.CollectResponse.created_at:type_name -> google.protobuf.Timestamp
	21, // 6: se.mantra.api.admin.CollectResponse.location:type_name -> se.mantra.api.common.Location
	23, // 7: se.mantra.api.admin.ListClientsResponse.clients:type_name -> se.mantra.api.common.ClientMeta
	19, // 8: se.mantra.api.admin.DomainDetails.created_at:type_name -> google.protobuf.Timestamp
	2,  // 9: se.mantra.api.admin.DomainAdminService.CreateUser:input_type -> se.mantra.api.admin.CreateUserRequest
	0,  // 10: se.mantra.api.admin.DomainAdminService.GetUser:input_type -> se.mantra.api.admin.GetUserRequest
	24, // 11: se.mantra.api.admin.DomainAdminService.ListUsers:input_type -> google.protobuf.Empty
	8,  // 12: se.mantra.api.admin.DomainAdminService.DeleteUser:input_type -> se.mantra.api.admin.DeleteUserRequest
	3,  // 13: se.mantra.api.admin.DomainAdminService.AddKey:input_type -> se.mantra.api.admin.AddKeyRequest
	4,  // 14: se.mantra.api.admin.DomainAdminService.RevokeKey:input_type -> se.mantra.api.admin.RevokeKeyRequest
	6,  // 15: se.mantra.api.admin.DomainAdminService.ActivateKey:input_type -> se.mantra.api.admin.ActivateKeyRequest
	12, // 16: se.mantra.api.admin.DomainAdminService.CollectChallenge:input_type -> se.mantra.api.admin.CollectRequest
	9,  // 17: se.mantra.api.admin.DomainAdminService.CreateClient:input_type -> se.mantra.api.admin.CreateClientRequest
	11, // 18: se.mantra.api.admin.DomainAdminService.DeleteClient:input_type -> se.mantra.api.admin.DeleteClientRequest
	15, // 19: se.mantra.api.admin.DomainAdminService.ListClients:input_type -> se.mantra.api.admin.ListClientsRequest
	17, // 20: se.mantra.api.admin.DomainAdminService.UpdateDomain:input_type -> se.mantra.api.admin.UpdateDomainDetailsRequest
	24, // 21: se.mantra.api.admin.DomainAdminService.GetDomain:input_type -> google.protobuf.Empty
	25, // 22: se.mantra.api.admin.DomainAdminService.CreateUser:output_type -> se.mantra.api.common.ChallengeResponse
	1,  // 23: se.mantra.api.admin.DomainAdminService.GetUser:output_type -> se.mantra.api.admin.GetUserResponse
	14, // 24: se.mantra.api.admin.DomainAdminService.ListUsers:output_type -> se.mantra.api.admin.ListUsersResponse
	24, // 25: se.mantra.api.admin.DomainAdminService.DeleteUser:output_type -> google.protobuf.Empty
	25, // 26: se.mantra.api.admin.DomainAdminService.AddKey:output_type -> se.mantra.api.common.ChallengeResponse
	5,  // 27: se.mantra.api.admin.DomainAdminService.RevokeKey:output_type -> se.mantra.api.admin.RevokeKeyResponse
	7,  // 28: se.mantra.api.admin.DomainAdminService.ActivateKey:output_type -> se.mantra.api.admin.ActivateKeyResponse
	13, // 29: se.mantra.api.admin.DomainAdminService.CollectChallenge:output_type -> se.mantra.api.admin.CollectResponse
	10, // 30: se.mantra.api.admin.DomainAdminService.CreateClient:output_type -> se.mantra.api.admin.CreateClientResponse
	24, // 31: se.mantra.api.admin.DomainAdminService.DeleteClient:output_type -> google.protobuf.Empty
	16, // 32: se.mantra.api.admin.DomainAdminService.ListClients:output_type -> se.mantra.api.admin.ListClientsResponse
	18, // 33: se.mantra.api.admin.DomainAdminService.UpdateDomain:output_type -> se.mantra.api.admin.DomainDetails
	18, // 34: se.mantra.api.admin.DomainAdminService.GetDomain:output_type -> se.mantra.api.admin.DomainDetails
	22, // [22:35] is the sub-list for method output_type
	9,  // [9:22] is the sub-list for method input_type
	9,  // [9:9] is the sub-list for extension type_name
	9,  // [9:9] is the sub-list for extension extendee
	0,  // [0:9] is the sub-list for field type_name
}

func init() { file_service_domain_admin_proto_init() }
func file_service_domain_admin_proto_init() {
	if File_service_domain_admin_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_service_domain_admin_proto_rawDesc), len(file_service_domain_admin_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   19,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_service_domain_admin_proto_goTypes,
		DependencyIndexes: file_service_domain_admin_proto_depIdxs,
		MessageInfos:      file_service_domain_admin_proto_msgTypes,
	}.Build()
	File_service_domain_admin_proto = out.File
	file_service_domain_admin_proto_goTypes = nil
	file_service_domain_admin_proto_depIdxs = nil
}
