// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             (unknown)
// source: service/domain_admin.proto

package admin

import (
	context "context"
	common "github.com/daedaluz/mantra-cli/lib/grpc/common"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	DomainAdminService_CreateUser_FullMethodName       = "/se.mantra.api.admin.DomainAdminService/CreateUser"
	DomainAdminService_GetUser_FullMethodName          = "/se.mantra.api.admin.DomainAdminService/GetUser"
	DomainAdminService_ListUsers_FullMethodName        = "/se.mantra.api.admin.DomainAdminService/ListUsers"
	DomainAdminService_DeleteUser_FullMethodName       = "/se.mantra.api.admin.DomainAdminService/DeleteUser"
	DomainAdminService_AddKey_FullMethodName           = "/se.mantra.api.admin.DomainAdminService/AddKey"
	DomainAdminService_RevokeKey_FullMethodName        = "/se.mantra.api.admin.DomainAdminService/RevokeKey"
	DomainAdminService_ActivateKey_FullMethodName      = "/se.mantra.api.admin.DomainAdminService/ActivateKey"
	DomainAdminService_CollectChallenge_FullMethodName = "/se.mantra.api.admin.DomainAdminService/CollectChallenge"
	DomainAdminService_CreateClient_FullMethodName     = "/se.mantra.api.admin.DomainAdminService/CreateClient"
	DomainAdminService_DeleteClient_FullMethodName     = "/se.mantra.api.admin.DomainAdminService/DeleteClient"
	DomainAdminService_ListClients_FullMethodName      = "/se.mantra.api.admin.DomainAdminService/ListClients"
	DomainAdminService_UpdateDomain_FullMethodName     = "/se.mantra.api.admin.DomainAdminService/UpdateDomain"
	DomainAdminService_GetDomain_FullMethodName        = "/se.mantra.api.admin.DomainAdminService/GetDomain"
	DomainAdminService_ListDevices_FullMethodName      = "/se.mantra.api.admin.DomainAdminService/ListDevices"
	DomainAdminService_UpdateDevice_FullMethodName     = "/se.mantra.api.admin.DomainAdminService/UpdateDevice"
	DomainAdminService_RemoveDevice_FullMethodName     = "/se.mantra.api.admin.DomainAdminService/RemoveDevice"
	DomainAdminService_AuditUser_FullMethodName        = "/se.mantra.api.admin.DomainAdminService/AuditUser"
	DomainAdminService_AuditChallenge_FullMethodName   = "/se.mantra.api.admin.DomainAdminService/AuditChallenge"
)

// DomainAdminServiceClient is the client API for DomainAdminService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type DomainAdminServiceClient interface {
	CreateUser(ctx context.Context, in *CreateUserRequest, opts ...grpc.CallOption) (*common.ChallengeResponse, error)
	GetUser(ctx context.Context, in *GetUserRequest, opts ...grpc.CallOption) (*GetUserResponse, error)
	ListUsers(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*ListUsersResponse, error)
	DeleteUser(ctx context.Context, in *DeleteUserRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	AddKey(ctx context.Context, in *AddKeyRequest, opts ...grpc.CallOption) (*common.ChallengeResponse, error)
	RevokeKey(ctx context.Context, in *RevokeKeyRequest, opts ...grpc.CallOption) (*RevokeKeyResponse, error)
	ActivateKey(ctx context.Context, in *ActivateKeyRequest, opts ...grpc.CallOption) (*ActivateKeyResponse, error)
	CollectChallenge(ctx context.Context, in *CollectRequest, opts ...grpc.CallOption) (*CollectResponse, error)
	CreateClient(ctx context.Context, in *CreateClientRequest, opts ...grpc.CallOption) (*CreateClientResponse, error)
	DeleteClient(ctx context.Context, in *DeleteClientRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	ListClients(ctx context.Context, in *ListClientsRequest, opts ...grpc.CallOption) (*ListClientsResponse, error)
	UpdateDomain(ctx context.Context, in *UpdateDomainDetailsRequest, opts ...grpc.CallOption) (*DomainDetails, error)
	GetDomain(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*DomainDetails, error)
	ListDevices(ctx context.Context, in *ListDevicesRequest, opts ...grpc.CallOption) (*ListDevicesResponse, error)
	UpdateDevice(ctx context.Context, in *UpdateDeviceRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	RemoveDevice(ctx context.Context, in *RemoveDeviceRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	AuditUser(ctx context.Context, in *DomainAuditUserRequest, opts ...grpc.CallOption) (*AuditUserResponse, error)
	AuditChallenge(ctx context.Context, in *DomainAuditChallengeRequest, opts ...grpc.CallOption) (*AuditEntry, error)
}

type domainAdminServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewDomainAdminServiceClient(cc grpc.ClientConnInterface) DomainAdminServiceClient {
	return &domainAdminServiceClient{cc}
}

func (c *domainAdminServiceClient) CreateUser(ctx context.Context, in *CreateUserRequest, opts ...grpc.CallOption) (*common.ChallengeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(common.ChallengeResponse)
	err := c.cc.Invoke(ctx, DomainAdminService_CreateUser_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *domainAdminServiceClient) GetUser(ctx context.Context, in *GetUserRequest, opts ...grpc.CallOption) (*GetUserResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetUserResponse)
	err := c.cc.Invoke(ctx, DomainAdminService_GetUser_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *domainAdminServiceClient) ListUsers(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*ListUsersResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListUsersResponse)
	err := c.cc.Invoke(ctx, DomainAdminService_ListUsers_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *domainAdminServiceClient) DeleteUser(ctx context.Context, in *DeleteUserRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, DomainAdminService_DeleteUser_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *domainAdminServiceClient) AddKey(ctx context.Context, in *AddKeyRequest, opts ...grpc.CallOption) (*common.ChallengeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(common.ChallengeResponse)
	err := c.cc.Invoke(ctx, DomainAdminService_AddKey_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *domainAdminServiceClient) RevokeKey(ctx context.Context, in *RevokeKeyRequest, opts ...grpc.CallOption) (*RevokeKeyResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RevokeKeyResponse)
	err := c.cc.Invoke(ctx, DomainAdminService_RevokeKey_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *domainAdminServiceClient) ActivateKey(ctx context.Context, in *ActivateKeyRequest, opts ...grpc.CallOption) (*ActivateKeyResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ActivateKeyResponse)
	err := c.cc.Invoke(ctx, DomainAdminService_ActivateKey_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *domainAdminServiceClient) CollectChallenge(ctx context.Context, in *CollectRequest, opts ...grpc.CallOption) (*CollectResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CollectResponse)
	err := c.cc.Invoke(ctx, DomainAdminService_CollectChallenge_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *domainAdminServiceClient) CreateClient(ctx context.Context, in *CreateClientRequest, opts ...grpc.CallOption) (*CreateClientResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateClientResponse)
	err := c.cc.Invoke(ctx, DomainAdminService_CreateClient_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *domainAdminServiceClient) DeleteClient(ctx context.Context, in *DeleteClientRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, DomainAdminService_DeleteClient_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *domainAdminServiceClient) ListClients(ctx context.Context, in *ListClientsRequest, opts ...grpc.CallOption) (*ListClientsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListClientsResponse)
	err := c.cc.Invoke(ctx, DomainAdminService_ListClients_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *domainAdminServiceClient) UpdateDomain(ctx context.Context, in *UpdateDomainDetailsRequest, opts ...grpc.CallOption) (*DomainDetails, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DomainDetails)
	err := c.cc.Invoke(ctx, DomainAdminService_UpdateDomain_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *domainAdminServiceClient) GetDomain(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*DomainDetails, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DomainDetails)
	err := c.cc.Invoke(ctx, DomainAdminService_GetDomain_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *domainAdminServiceClient) ListDevices(ctx context.Context, in *ListDevicesRequest, opts ...grpc.CallOption) (*ListDevicesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListDevicesResponse)
	err := c.cc.Invoke(ctx, DomainAdminService_ListDevices_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *domainAdminServiceClient) UpdateDevice(ctx context.Context, in *UpdateDeviceRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, DomainAdminService_UpdateDevice_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *domainAdminServiceClient) RemoveDevice(ctx context.Context, in *RemoveDeviceRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, DomainAdminService_RemoveDevice_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *domainAdminServiceClient) AuditUser(ctx context.Context, in *DomainAuditUserRequest, opts ...grpc.CallOption) (*AuditUserResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AuditUserResponse)
	err := c.cc.Invoke(ctx, DomainAdminService_AuditUser_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *domainAdminServiceClient) AuditChallenge(ctx context.Context, in *DomainAuditChallengeRequest, opts ...grpc.CallOption) (*AuditEntry, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AuditEntry)
	err := c.cc.Invoke(ctx, DomainAdminService_AuditChallenge_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DomainAdminServiceServer is the server API for DomainAdminService service.
// All implementations should embed UnimplementedDomainAdminServiceServer
// for forward compatibility.
type DomainAdminServiceServer interface {
	CreateUser(context.Context, *CreateUserRequest) (*common.ChallengeResponse, error)
	GetUser(context.Context, *GetUserRequest) (*GetUserResponse, error)
	ListUsers(context.Context, *emptypb.Empty) (*ListUsersResponse, error)
	DeleteUser(context.Context, *DeleteUserRequest) (*emptypb.Empty, error)
	AddKey(context.Context, *AddKeyRequest) (*common.ChallengeResponse, error)
	RevokeKey(context.Context, *RevokeKeyRequest) (*RevokeKeyResponse, error)
	ActivateKey(context.Context, *ActivateKeyRequest) (*ActivateKeyResponse, error)
	CollectChallenge(context.Context, *CollectRequest) (*CollectResponse, error)
	CreateClient(context.Context, *CreateClientRequest) (*CreateClientResponse, error)
	DeleteClient(context.Context, *DeleteClientRequest) (*emptypb.Empty, error)
	ListClients(context.Context, *ListClientsRequest) (*ListClientsResponse, error)
	UpdateDomain(context.Context, *UpdateDomainDetailsRequest) (*DomainDetails, error)
	GetDomain(context.Context, *emptypb.Empty) (*DomainDetails, error)
	ListDevices(context.Context, *ListDevicesRequest) (*ListDevicesResponse, error)
	UpdateDevice(context.Context, *UpdateDeviceRequest) (*emptypb.Empty, error)
	RemoveDevice(context.Context, *RemoveDeviceRequest) (*emptypb.Empty, error)
	AuditUser(context.Context, *DomainAuditUserRequest) (*AuditUserResponse, error)
	AuditChallenge(context.Context, *DomainAuditChallengeRequest) (*AuditEntry, error)
}

// UnimplementedDomainAdminServiceServer should be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedDomainAdminServiceServer struct{}

func (UnimplementedDomainAdminServiceServer) CreateUser(context.Context, *CreateUserRequest) (*common.ChallengeResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateUser not implemented")
}
func (UnimplementedDomainAdminServiceServer) GetUser(context.Context, *GetUserRequest) (*GetUserResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetUser not implemented")
}
func (UnimplementedDomainAdminServiceServer) ListUsers(context.Context, *emptypb.Empty) (*ListUsersResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListUsers not implemented")
}
func (UnimplementedDomainAdminServiceServer) DeleteUser(context.Context, *DeleteUserRequest) (*emptypb.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteUser not implemented")
}
func (UnimplementedDomainAdminServiceServer) AddKey(context.Context, *AddKeyRequest) (*common.ChallengeResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method AddKey not implemented")
}
func (UnimplementedDomainAdminServiceServer) RevokeKey(context.Context, *RevokeKeyRequest) (*RevokeKeyResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RevokeKey not implemented")
}
func (UnimplementedDomainAdminServiceServer) ActivateKey(context.Context, *ActivateKeyRequest) (*ActivateKeyResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ActivateKey not implemented")
}
func (UnimplementedDomainAdminServiceServer) CollectChallenge(context.Context, *CollectRequest) (*CollectResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CollectChallenge not implemented")
}
func (UnimplementedDomainAdminServiceServer) CreateClient(context.Context, *CreateClientRequest) (*CreateClientResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateClient not implemented")
}
func (UnimplementedDomainAdminServiceServer) DeleteClient(context.Context, *DeleteClientRequest) (*emptypb.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteClient not implemented")
}
func (UnimplementedDomainAdminServiceServer) ListClients(context.Context, *ListClientsRequest) (*ListClientsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListClients not implemented")
}
func (UnimplementedDomainAdminServiceServer) UpdateDomain(context.Context, *UpdateDomainDetailsRequest) (*DomainDetails, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateDomain not implemented")
}
func (UnimplementedDomainAdminServiceServer) GetDomain(context.Context, *emptypb.Empty) (*DomainDetails, error) {
	return nil, status.Error(codes.Unimplemented, "method GetDomain not implemented")
}
func (UnimplementedDomainAdminServiceServer) ListDevices(context.Context, *ListDevicesRequest) (*ListDevicesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListDevices not implemented")
}
func (UnimplementedDomainAdminServiceServer) UpdateDevice(context.Context, *UpdateDeviceRequest) (*emptypb.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateDevice not implemented")
}
func (UnimplementedDomainAdminServiceServer) RemoveDevice(context.Context, *RemoveDeviceRequest) (*emptypb.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method RemoveDevice not implemented")
}
func (UnimplementedDomainAdminServiceServer) AuditUser(context.Context, *DomainAuditUserRequest) (*AuditUserResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method AuditUser not implemented")
}
func (UnimplementedDomainAdminServiceServer) AuditChallenge(context.Context, *DomainAuditChallengeRequest) (*AuditEntry, error) {
	return nil, status.Error(codes.Unimplemented, "method AuditChallenge not implemented")
}
func (UnimplementedDomainAdminServiceServer) testEmbeddedByValue() {}

// UnsafeDomainAdminServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to DomainAdminServiceServer will
// result in compilation errors.
type UnsafeDomainAdminServiceServer interface {
	mustEmbedUnimplementedDomainAdminServiceServer()
}

func RegisterDomainAdminServiceServer(s grpc.ServiceRegistrar, srv DomainAdminServiceServer) {
	// If the following call panics, it indicates UnimplementedDomainAdminServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&DomainAdminService_ServiceDesc, srv)
}

func _DomainAdminService_CreateUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DomainAdminServiceServer).CreateUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DomainAdminService_CreateUser_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DomainAdminServiceServer).CreateUser(ctx, req.(*CreateUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DomainAdminService_GetUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DomainAdminServiceServer).GetUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DomainAdminService_GetUser_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DomainAdminServiceServer).GetUser(ctx, req.(*GetUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DomainAdminService_ListUsers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DomainAdminServiceServer).ListUsers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DomainAdminService_ListUsers_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DomainAdminServiceServer).ListUsers(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _DomainAdminService_DeleteUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DomainAdminServiceServer).DeleteUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DomainAdminService_DeleteUser_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DomainAdminServiceServer).DeleteUser(ctx, req.(*DeleteUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DomainAdminService_AddKey_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddKeyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DomainAdminServiceServer).AddKey(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DomainAdminService_AddKey_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DomainAdminServiceServer).AddKey(ctx, req.(*AddKeyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DomainAdminService_RevokeKey_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RevokeKeyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DomainAdminServiceServer).RevokeKey(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DomainAdminService_RevokeKey_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DomainAdminServiceServer).RevokeKey(ctx, req.(*RevokeKeyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DomainAdminService_ActivateKey_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ActivateKeyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DomainAdminServiceServer).ActivateKey(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DomainAdminService_ActivateKey_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DomainAdminServiceServer).ActivateKey(ctx, req.(*ActivateKeyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DomainAdminService_CollectChallenge_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CollectRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DomainAdminServiceServer).CollectChallenge(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DomainAdminService_CollectChallenge_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DomainAdminServiceServer).CollectChallenge(ctx, req.(*CollectRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DomainAdminService_CreateClient_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateClientRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DomainAdminServiceServer).CreateClient(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DomainAdminService_CreateClient_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DomainAdminServiceServer).CreateClient(ctx, req.(*CreateClientRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DomainAdminService_DeleteClient_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteClientRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DomainAdminServiceServer).DeleteClient(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DomainAdminService_DeleteClient_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DomainAdminServiceServer).DeleteClient(ctx, req.(*DeleteClientRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DomainAdminService_ListClients_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListClientsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DomainAdminServiceServer).ListClients(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DomainAdminService_ListClients_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DomainAdminServiceServer).ListClients(ctx, req.(*ListClientsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DomainAdminService_UpdateDomain_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateDomainDetailsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DomainAdminServiceServer).UpdateDomain(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DomainAdminService_UpdateDomain_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DomainAdminServiceServer).UpdateDomain(ctx, req.(*UpdateDomainDetailsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DomainAdminService_GetDomain_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DomainAdminServiceServer).GetDomain(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DomainAdminService_GetDomain_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DomainAdminServiceServer).GetDomain(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _DomainAdminService_ListDevices_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListDevicesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DomainAdminServiceServer).ListDevices(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DomainAdminService_ListDevices_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DomainAdminServiceServer).ListDevices(ctx, req.(*ListDevicesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DomainAdminService_UpdateDevice_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateDeviceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DomainAdminServiceServer).UpdateDevice(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DomainAdminService_UpdateDevice_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DomainAdminServiceServer).UpdateDevice(ctx, req.(*UpdateDeviceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DomainAdminService_RemoveDevice_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RemoveDeviceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DomainAdminServiceServer).RemoveDevice(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DomainAdminService_RemoveDevice_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DomainAdminServiceServer).RemoveDevice(ctx, req.(*RemoveDeviceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DomainAdminService_AuditUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DomainAuditUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DomainAdminServiceServer).AuditUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DomainAdminService_AuditUser_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DomainAdminServiceServer).AuditUser(ctx, req.(*DomainAuditUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DomainAdminService_AuditChallenge_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DomainAuditChallengeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DomainAdminServiceServer).AuditChallenge(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DomainAdminService_AuditChallenge_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DomainAdminServiceServer).AuditChallenge(ctx, req.(*DomainAuditChallengeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// DomainAdminService_ServiceDesc is the grpc.ServiceDesc for DomainAdminService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var DomainAdminService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "se.mantra.api.admin.DomainAdminService",
	HandlerType: (*DomainAdminServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateUser",
			Handler:    _DomainAdminService_CreateUser_Handler,
		},
		{
			MethodName: "GetUser",
			Handler:    _DomainAdminService_GetUser_Handler,
		},
		{
			MethodName: "ListUsers",
			Handler:    _DomainAdminService_ListUsers_Handler,
		},
		{
			MethodName: "DeleteUser",
			Handler:    _DomainAdminService_DeleteUser_Handler,
		},
		{
			MethodName: "AddKey",
			Handler:    _DomainAdminService_AddKey_Handler,
		},
		{
			MethodName: "RevokeKey",
			Handler:    _DomainAdminService_RevokeKey_Handler,
		},
		{
			MethodName: "ActivateKey",
			Handler:    _DomainAdminService_ActivateKey_Handler,
		},
		{
			MethodName: "CollectChallenge",
			Handler:    _DomainAdminService_CollectChallenge_Handler,
		},
		{
			MethodName: "CreateClient",
			Handler:    _DomainAdminService_CreateClient_Handler,
		},
		{
			MethodName: "DeleteClient",
			Handler:    _DomainAdminService_DeleteClient_Handler,
		},
		{
			MethodName: "ListClients",
			Handler:    _DomainAdminService_ListClients_Handler,
		},
		{
			MethodName: "UpdateDomain",
			Handler:    _DomainAdminService_UpdateDomain_Handler,
		},
		{
			MethodName: "GetDomain",
			Handler:    _DomainAdminService_GetDomain_Handler,
		},
		{
			MethodName: "ListDevices",
			Handler:    _DomainAdminService_ListDevices_Handler,
		},
		{
			MethodName: "UpdateDevice",
			Handler:    _DomainAdminService_UpdateDevice_Handler,
		},
		{
			MethodName: "RemoveDevice",
			Handler:    _DomainAdminService_RemoveDevice_Handler,
		},
		{
			MethodName: "AuditUser",
			Handler:    _DomainAdminService_AuditUser_Handler,
		},
		{
			MethodName: "AuditChallenge",
			Handler:    _DomainAdminService_AuditChallenge_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "service/domain_admin.proto",
}
