// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: service/platform_admin.proto

package admin

import (
	common "github.com/daedaluz/mantra-cli/lib/grpc/common"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateDomainRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Domain           string                 `protobuf:"bytes,1,opt,name=domain,proto3" json:"domain,omitempty"`
	Name             string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description      string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Algorithms       []int64                `protobuf:"varint,4,rep,packed,name=algorithms,proto3" json:"algorithms,omitempty"`
	RegistrationPath string                 `protobuf:"bytes,5,opt,name=registration_path,json=registrationPath,proto3" json:"registration_path,omitempty"`
	SignPath         string                 `protobuf:"bytes,6,opt,name=sign_path,json=signPath,proto3" json:"sign_path,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *CreateDomainRequest) Reset() {
	*x = CreateDomainRequest{}
	mi := &file_service_platform_admin_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateDomainRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateDomainRequest) ProtoMessage() {}

func (x *CreateDomainRequest) ProtoReflect() protoreflect.Message {
	mi := &file_service_platform_admin_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateDomainRequest.ProtoReflect.Descriptor instead.
func (*CreateDomainRequest) Descriptor() ([]byte, []int) {
	return file_service_platform_admin_proto_rawDescGZIP(), []int{0}
}

func (x *CreateDomainRequest) GetDomain() string {
	if x != nil {
		return x.Domain
	}
	return ""
}

func (x *CreateDomainRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateDomainRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *CreateDomainRequest) GetAlgorithms() []int64 {
	if x != nil {
		return x.Algorithms
	}
	return nil
}

func (x *CreateDomainRequest) GetRegistrationPath() string {
	if x != nil {
		return x.RegistrationPath
	}
	return ""
}

func (x *CreateDomainRequest) GetSignPath() string {
	if x != nil {
		return x.SignPath
	}
	return ""
}

type CreateDomainResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ClientId      string                 `protobuf:"bytes,5,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	Secret        string                 `protobuf:"bytes,6,opt,name=secret,proto3" json:"secret,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateDomainResponse) Reset() {
	*x = CreateDomainResponse{}
	mi := &file_service_platform_admin_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateDomainResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateDomainResponse) ProtoMessage() {}

func (x *CreateDomainResponse) ProtoReflect() protoreflect.Message {
	mi := &file_service_platform_admin_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateDomainResponse.ProtoReflect.Descriptor instead.
func (*CreateDomainResponse) Descriptor() ([]byte, []int) {
	return file_service_platform_admin_proto_rawDescGZIP(), []int{1}
}

func (x *CreateDomainResponse) GetClientId() string {
	if x != nil {
		return x.ClientId
	}
	return ""
}

func (x *CreateDomainResponse) GetSecret() string {
	if x != nil {
		return x.Secret
	}
	return ""
}

type DeleteDomainRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Domain        string                 `protobuf:"bytes,1,opt,name=domain,proto3" json:"domain,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteDomainRequest) Reset() {
	*x = DeleteDomainRequest{}
	mi := &file_service_platform_admin_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteDomainRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteDomainRequest) ProtoMessage() {}

func (x *DeleteDomainRequest) ProtoReflect() protoreflect.Message {
	mi := &file_service_platform_admin_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteDomainRequest.ProtoReflect.Descriptor instead.
func (*DeleteDomainRequest) Descriptor() ([]byte, []int) {
	return file_service_platform_admin_proto_rawDescGZIP(), []int{2}
}

func (x *DeleteDomainRequest) GetDomain() string {
	if x != nil {
		return x.Domain
	}
	return ""
}

type Domain struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Domain           string                 `protobuf:"bytes,1,opt,name=domain,proto3" json:"domain,omitempty"`
	Name             string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description      string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Algorithms       []int64                `protobuf:"varint,4,rep,packed,name=algorithms,proto3" json:"algorithms,omitempty"`
	CreatedAt        *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	RegistrationPath string                 `protobuf:"bytes,6,opt,name=registration_path,json=registrationPath,proto3" json:"registration_path,omitempty"`
	SignPath         string                 `protobuf:"bytes,7,opt,name=sign_path,json=signPath,proto3" json:"sign_path,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *Domain) Reset() {
	*x = Domain{}
	mi := &file_service_platform_admin_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Domain) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Domain) ProtoMessage() {}

func (x *Domain) ProtoReflect() protoreflect.Message {
	mi := &file_service_platform_admin_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Domain.ProtoReflect.Descriptor instead.
func (*Domain) Descriptor() ([]byte, []int) {
	return file_service_platform_admin_proto_rawDescGZIP(), []int{3}
}

func (x *Domain) GetDomain() string {
	if x != nil {
		return x.Domain
	}
	return ""
}

func (x *Domain) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Domain) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Domain) GetAlgorithms() []int64 {
	if x != nil {
		return x.Algorithms
	}
	return nil
}

func (x *Domain) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Domain) GetRegistrationPath() string {
	if x != nil {
		return x.RegistrationPath
	}
	return ""
}

func (x *Domain) GetSignPath() string {
	if x != nil {
		return x.SignPath
	}
	return ""
}

type ListDomainsRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Optional filter: if provided, only return domains matching these names
	Domains       []string `protobuf:"bytes,1,rep,name=domains,proto3" json:"domains,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListDomainsRequest) Reset() {
	*x = ListDomainsRequest{}
	mi := &file_service_platform_admin_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListDomainsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListDomainsRequest) ProtoMessage() {}

func (x *ListDomainsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_service_platform_admin_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListDomainsRequest.ProtoReflect.Descriptor instead.
func (*ListDomainsRequest) Descriptor() ([]byte, []int) {
	return file_service_platform_admin_proto_rawDescGZIP(), []int{4}
}

func (x *ListDomainsRequest) GetDomains() []string {
	if x != nil {
		return x.Domains
	}
	return nil
}

type ListDomainsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Domains       []*Domain              `protobuf:"bytes,1,rep,name=domains,proto3" json:"domains,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListDomainsResponse) Reset() {
	*x = ListDomainsResponse{}
	mi := &file_service_platform_admin_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListDomainsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListDomainsResponse) ProtoMessage() {}

func (x *ListDomainsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_service_platform_admin_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListDomainsResponse.ProtoReflect.Descriptor instead.
func (*ListDomainsResponse) Descriptor() ([]byte, []int) {
	return file_service_platform_admin_proto_rawDescGZIP(), []int{5}
}

func (x *ListDomainsResponse) GetDomains() []*Domain {
	if x != nil {
		return x.Domains
	}
	return nil
}

type GetDomainRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Domain        string                 `protobuf:"bytes,1,opt,name=domain,proto3" json:"domain,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDomainRequest) Reset() {
	*x = GetDomainRequest{}
	mi := &file_service_platform_admin_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDomainRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDomainRequest) ProtoMessage() {}

func (x *GetDomainRequest) ProtoReflect() protoreflect.Message {
	mi := &file_service_platform_admin_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDomainRequest.ProtoReflect.Descriptor instead.
func (*GetDomainRequest) Descriptor() ([]byte, []int) {
	return file_service_platform_admin_proto_rawDescGZIP(), []int{6}
}

func (x *GetDomainRequest) GetDomain() string {
	if x != nil {
		return x.Domain
	}
	return ""
}

type UpdateDomainRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Domain           string                 `protobuf:"bytes,1,opt,name=domain,proto3" json:"domain,omitempty"`
	Name             string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description      string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Algorithms       []int64                `protobuf:"varint,4,rep,packed,name=algorithms,proto3" json:"algorithms,omitempty"`
	RegistrationPath string                 `protobuf:"bytes,5,opt,name=registration_path,json=registrationPath,proto3" json:"registration_path,omitempty"`
	SignPath         string                 `protobuf:"bytes,6,opt,name=sign_path,json=signPath,proto3" json:"sign_path,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *UpdateDomainRequest) Reset() {
	*x = UpdateDomainRequest{}
	mi := &file_service_platform_admin_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateDomainRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateDomainRequest) ProtoMessage() {}

func (x *UpdateDomainRequest) ProtoReflect() protoreflect.Message {
	mi := &file_service_platform_admin_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateDomainRequest.ProtoReflect.Descriptor instead.
func (*UpdateDomainRequest) Descriptor() ([]byte, []int) {
	return file_service_platform_admin_proto_rawDescGZIP(), []int{7}
}

func (x *UpdateDomainRequest) GetDomain() string {
	if x != nil {
		return x.Domain
	}
	return ""
}

func (x *UpdateDomainRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UpdateDomainRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *UpdateDomainRequest) GetAlgorithms() []int64 {
	if x != nil {
		return x.Algorithms
	}
	return nil
}

func (x *UpdateDomainRequest) GetRegistrationPath() string {
	if x != nil {
		return x.RegistrationPath
	}
	return ""
}

func (x *UpdateDomainRequest) GetSignPath() string {
	if x != nil {
		return x.SignPath
	}
	return ""
}

type ListAdminClientsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Domain        string                 `protobuf:"bytes,1,opt,name=domain,proto3" json:"domain,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListAdminClientsRequest) Reset() {
	*x = ListAdminClientsRequest{}
	mi := &file_service_platform_admin_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListAdminClientsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAdminClientsRequest) ProtoMessage() {}

func (x *ListAdminClientsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_service_platform_admin_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAdminClientsRequest.ProtoReflect.Descriptor instead.
func (*ListAdminClientsRequest) Descriptor() ([]byte, []int) {
	return file_service_platform_admin_proto_rawDescGZIP(), []int{8}
}

func (x *ListAdminClientsRequest) GetDomain() string {
	if x != nil {
		return x.Domain
	}
	return ""
}

type ListAdminClientsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Clients       []*common.ClientMeta   `protobuf:"bytes,1,rep,name=clients,proto3" json:"clients,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListAdminClientsResponse) Reset() {
	*x = ListAdminClientsResponse{}
	mi := &file_service_platform_admin_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListAdminClientsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAdminClientsResponse) ProtoMessage() {}

func (x *ListAdminClientsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_service_platform_admin_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAdminClientsResponse.ProtoReflect.Descriptor instead.
func (*ListAdminClientsResponse) Descriptor() ([]byte, []int) {
	return file_service_platform_admin_proto_rawDescGZIP(), []int{9}
}

func (x *ListAdminClientsResponse) GetClients() []*common.ClientMeta {
	if x != nil {
		return x.Clients
	}
	return nil
}

var File_service_platform_admin_proto protoreflect.FileDescriptor

const file_service_platform_admin_proto_rawDesc = "" +
	"\n" +
	"\x1cservice/platform_admin.proto\x12\x13se.mantra.api.admin\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1bgoogle/protobuf/empty.proto\x1a\x13common/common.proto\"\xcd\x01\n" +
	"\x13CreateDomainRequest\x12\x16\n" +
	"\x06domain\x18\x01 \x01(\tR\x06domain\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x1e\n" +
	"\n" +
	"algorithms\x18\x04 \x03(\x03R\n" +
	"algorithms\x12+\n" +
	"\x11registration_path\x18\x05 \x01(\tR\x10registrationPath\x12\x1b\n" +
	"\tsign_path\x18\x06 \x01(\tR\bsignPath\"K\n" +
	"\x14CreateDomainResponse\x12\x1b\n" +
	"\tclient_id\x18\x05 \x01(\tR\bclientId\x12\x16\n" +
	"\x06secret\x18\x06 \x01(\tR\x06secret\"-\n" +
	"\x13DeleteDomainRequest\x12\x16\n" +
	"\x06domain\x18\x01 \x01(\tR\x06domain\"\xfb\x01\n" +
	"\x06Domain\x12\x16\n" +
	"\x06domain\x18\x01 \x01(\tR\x06domain\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x1e\n" +
	"\n" +
	"algorithms\x18\x04 \x03(\x03R\n" +
	"algorithms\x129\n" +
	"\n" +
	"created_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x12+\n" +
	"\x11registration_path\x18\x06 \x01(\tR\x10registrationPath\x12\x1b\n" +
	"\tsign_path\x18\a \x01(\tR\bsignPath\".\n" +
	"\x12ListDomainsRequest\x12\x18\n" +
	"\adomains\x18\x01 \x03(\tR\adomains\"L\n" +
	"\x13ListDomainsResponse\x125\n" +
	"\adomains\x18\x01 \x03(\v2\x1b.se.mantra.api.admin.DomainR\adomains\"*\n" +
	"\x10GetDomainRequest\x12\x16\n" +
	"\x06domain\x18\x01 \x01(\tR\x06domain\"\xcd\x01\n" +
	"\x13UpdateDomainRequest\x12\x16\n" +
	"\x06domain\x18\x01 \x01(\tR\x06domain\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x1e\n" +
	"\n" +
	"algorithms\x18\x04 \x03(\x03R\n" +
	"algorithms\x12+\n" +
	"\x11registration_path\x18\x05 \x01(\tR\x10registrationPath\x12\x1b\n" +
	"\tsign_path\x18\x06 \x01(\tR\bsignPath\"1\n" +
	"\x17ListAdminClientsRequest\x12\x16\n" +
	"\x06domain\x18\x01 \x01(\tR\x06domain\"V\n" +
	"\x18ListAdminClientsResponse\x12:\n" +
	"\aclients\x18\x01 \x03(\v2 .se.mantra.api.common.ClientMetaR\aclients2\xc8\x04\n" +
	"\x14PlatformAdminService\x12c\n" +
	"\fCreateDomain\x12(.se.mantra.api.admin.CreateDomainRequest\x1a).se.mantra.api.admin.CreateDomainResponse\x12P\n" +
	"\fDeleteDomain\x12(.se.mantra.api.admin.DeleteDomainRequest\x1a\x16.google.protobuf.Empty\x12`\n" +
	"\vListDomains\x12'.se.mantra.api.admin.ListDomainsRequest\x1a(.se.mantra.api.admin.ListDomainsResponse\x12O\n" +
	"\tGetDomain\x12%.se.mantra.api.admin.GetDomainRequest\x1a\x1b.se.mantra.api.admin.Domain\x12U\n" +
	"\fUpdateDomain\x12(.se.mantra.api.admin.UpdateDomainRequest\x1a\x1b.se.mantra.api.admin.Domain\x12o\n" +
	"\x10ListAdminClients\x12,.se.mantra.api.admin.ListAdminClientsRequest\x1a-.se.mantra.api.admin.ListAdminClientsResponseB/Z-github.com/daedaluz/mantra-cli/lib/grpc/adminb\x06proto3"

var (
	file_service_platform_admin_proto_rawDescOnce sync.Once
	file_service_platform_admin_proto_rawDescData []byte
)

func file_service_platform_admin_proto_rawDescGZIP() []byte {
	file_service_platform_admin_proto_rawDescOnce.Do(func() {
		file_service_platform_admin_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_service_platform_admin_proto_rawDesc), len(file_service_platform_admin_proto_rawDesc)))
	})
	return file_service_platform_admin_proto_rawDescData
}

var file_service_platform_admin_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_service_platform_admin_proto_goTypes = []any{
	(*CreateDomainRequest)(nil),      // 0: se.mantra.api.admin.CreateDomainRequest
	(*CreateDomainResponse)(nil),     // 1: se.mantra.api.admin.CreateDomainResponse
	(*DeleteDomainRequest)(nil),      // 2: se.mantra.api.admin.DeleteDomainRequest
	(*Domain)(nil),                   // 3: se.mantra.api.admin.Domain
	(*ListDomainsRequest)(nil),       // 4: se.mantra.api.admin.ListDomainsRequest
	(*ListDomainsResponse)(nil),      // 5: se.mantra.api.admin.ListDomainsResponse
	(*GetDomainRequest)(nil),         // 6: se.mantra.api.admin.GetDomainRequest
	(*UpdateDomainRequest)(nil),      // 7: se.mantra.api.admin.UpdateDomainRequest
	(*ListAdminClientsRequest)(nil),  // 8: se.mantra.api.admin.ListAdminClientsRequest
	(*ListAdminClientsResponse)(nil), // 9: se.mantra.api.admin.ListAdminClientsResponse
	(*timestamppb.Timestamp)(nil),    // 10: google.protobuf.Timestamp
	(*common.ClientMeta)(nil),        // 11: se.mantra.api.common.ClientMeta
	(*emptypb.Empty)(nil),            // 12: google.protobuf.Empty
}
var file_service_platform_admin_proto_depIdxs = []int32{
	10, // 0: se.mantra.api.admin.Domain.created_at:type_name -> google.protobuf.Timestamp
	3,  // 1: se.mantra.api.admin.ListDomainsResponse.domains:type_name -> se.mantra.api.admin.Domain
	11, // 2: se.mantra.api.admin.ListAdminClientsResponse.clients:type_name -> se.mantra.api.common.ClientMeta
	0,  // 3: se.mantra.api.admin.PlatformAdminService.CreateDomain:input_type -> se.mantra.api.admin.CreateDomainRequest
	2,  // 4: se.mantra.api.admin.PlatformAdminService.DeleteDomain:input_type -> se.mantra.api.admin.DeleteDomainRequest
	4,  // 5: se.mantra.api.admin.PlatformAdminService.ListDomains:input_type -> se.mantra.api.admin.ListDomainsRequest
	6,  // 6: se.mantra.api.admin.PlatformAdminService.GetDomain:input_type -> se.mantra.api.admin.GetDomainRequest
	7,  // 7: se.mantra.api.admin.PlatformAdminService.UpdateDomain:input_type -> se.mantra.api.admin.UpdateDomainRequest
	8,  // 8: se.mantra.api.admin.PlatformAdminService.ListAdminClients:input_type -> se.mantra.api.admin.ListAdminClientsRequest
	1,  // 9: se.mantra.api.admin.PlatformAdminService.CreateDomain:output_type -> se.mantra.api.admin.CreateDomainResponse
	12, // 10: se.mantra.api.admin.PlatformAdminService.DeleteDomain:output_type -> google.protobuf.Empty
	5,  // 11: se.mantra.api.admin.PlatformAdminService.ListDomains:output_type -> se.mantra.api.admin.ListDomainsResponse
	3,  // 12: se.mantra.api.admin.PlatformAdminService.GetDomain:output_type -> se.mantra.api.admin.Domain
	3,  // 13: se.mantra.api.admin.PlatformAdminService.UpdateDomain:output_type -> se.mantra.api.admin.Domain
	9,  // 14: se.mantra.api.admin.PlatformAdminService.ListAdminClients:output_type -> se.mantra.api.admin.ListAdminClientsResponse
	9,  // [9:15] is the sub-list for method output_type
	3,  // [3:9] is the sub-list for method input_type
	3,  // [3:3] is the sub-list for extension type_name
	3,  // [3:3] is the sub-list for extension extendee
	0,  // [0:3] is the sub-list for field type_name
}

func init() { file_service_platform_admin_proto_init() }
func file_service_platform_admin_proto_init() {
	if File_service_platform_admin_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_service_platform_admin_proto_rawDesc), len(file_service_platform_admin_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_service_platform_admin_proto_goTypes,
		DependencyIndexes: file_service_platform_admin_proto_depIdxs,
		MessageInfos:      file_service_platform_admin_proto_msgTypes,
	}.Build()
	File_service_platform_admin_proto = out.File
	file_service_platform_admin_proto_goTypes = nil
	file_service_platform_admin_proto_depIdxs = nil
}
