// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             (unknown)
// source: service/platform_admin.proto

package admin

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	PlatformAdminService_CreateDomain_FullMethodName     = "/se.mantra.api.admin.PlatformAdminService/CreateDomain"
	PlatformAdminService_DeleteDomain_FullMethodName     = "/se.mantra.api.admin.PlatformAdminService/DeleteDomain"
	PlatformAdminService_ListDomains_FullMethodName      = "/se.mantra.api.admin.PlatformAdminService/ListDomains"
	PlatformAdminService_GetDomain_FullMethodName        = "/se.mantra.api.admin.PlatformAdminService/GetDomain"
	PlatformAdminService_UpdateDomain_FullMethodName     = "/se.mantra.api.admin.PlatformAdminService/UpdateDomain"
	PlatformAdminService_ListAdminClients_FullMethodName = "/se.mantra.api.admin.PlatformAdminService/ListAdminClients"
	PlatformAdminService_AuditUser_FullMethodName        = "/se.mantra.api.admin.PlatformAdminService/AuditUser"
	PlatformAdminService_AuditChallenge_FullMethodName   = "/se.mantra.api.admin.PlatformAdminService/AuditChallenge"
)

// PlatformAdminServiceClient is the client API for PlatformAdminService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type PlatformAdminServiceClient interface {
	CreateDomain(ctx context.Context, in *CreateDomainRequest, opts ...grpc.CallOption) (*CreateDomainResponse, error)
	DeleteDomain(ctx context.Context, in *DeleteDomainRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	ListDomains(ctx context.Context, in *ListDomainsRequest, opts ...grpc.CallOption) (*ListDomainsResponse, error)
	GetDomain(ctx context.Context, in *GetDomainRequest, opts ...grpc.CallOption) (*Domain, error)
	UpdateDomain(ctx context.Context, in *UpdateDomainRequest, opts ...grpc.CallOption) (*Domain, error)
	ListAdminClients(ctx context.Context, in *ListAdminClientsRequest, opts ...grpc.CallOption) (*ListAdminClientsResponse, error)
	AuditUser(ctx context.Context, in *AuditUserRequest, opts ...grpc.CallOption) (*AuditUserResponse, error)
	AuditChallenge(ctx context.Context, in *AuditChallengeRequest, opts ...grpc.CallOption) (*AuditEntry, error)
}

type platformAdminServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewPlatformAdminServiceClient(cc grpc.ClientConnInterface) PlatformAdminServiceClient {
	return &platformAdminServiceClient{cc}
}

func (c *platformAdminServiceClient) CreateDomain(ctx context.Context, in *CreateDomainRequest, opts ...grpc.CallOption) (*CreateDomainResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateDomainResponse)
	err := c.cc.Invoke(ctx, PlatformAdminService_CreateDomain_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *platformAdminServiceClient) DeleteDomain(ctx context.Context, in *DeleteDomainRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, PlatformAdminService_DeleteDomain_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *platformAdminServiceClient) ListDomains(ctx context.Context, in *ListDomainsRequest, opts ...grpc.CallOption) (*ListDomainsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListDomainsResponse)
	err := c.cc.Invoke(ctx, PlatformAdminService_ListDomains_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *platformAdminServiceClient) GetDomain(ctx context.Context, in *GetDomainRequest, opts ...grpc.CallOption) (*Domain, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Domain)
	err := c.cc.Invoke(ctx, PlatformAdminService_GetDomain_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *platformAdminServiceClient) UpdateDomain(ctx context.Context, in *UpdateDomainRequest, opts ...grpc.CallOption) (*Domain, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Domain)
	err := c.cc.Invoke(ctx, PlatformAdminService_UpdateDomain_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *platformAdminServiceClient) ListAdminClients(ctx context.Context, in *ListAdminClientsRequest, opts ...grpc.CallOption) (*ListAdminClientsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListAdminClientsResponse)
	err := c.cc.Invoke(ctx, PlatformAdminService_ListAdminClients_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *platformAdminServiceClient) AuditUser(ctx context.Context, in *AuditUserRequest, opts ...grpc.CallOption) (*AuditUserResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AuditUserResponse)
	err := c.cc.Invoke(ctx, PlatformAdminService_AuditUser_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *platformAdminServiceClient) AuditChallenge(ctx context.Context, in *AuditChallengeRequest, opts ...grpc.CallOption) (*AuditEntry, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AuditEntry)
	err := c.cc.Invoke(ctx, PlatformAdminService_AuditChallenge_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PlatformAdminServiceServer is the server API for PlatformAdminService service.
// All implementations should embed UnimplementedPlatformAdminServiceServer
// for forward compatibility.
type PlatformAdminServiceServer interface {
	CreateDomain(context.Context, *CreateDomainRequest) (*CreateDomainResponse, error)
	DeleteDomain(context.Context, *DeleteDomainRequest) (*emptypb.Empty, error)
	ListDomains(context.Context, *ListDomainsRequest) (*ListDomainsResponse, error)
	GetDomain(context.Context, *GetDomainRequest) (*Domain, error)
	UpdateDomain(context.Context, *UpdateDomainRequest) (*Domain, error)
	ListAdminClients(context.Context, *ListAdminClientsRequest) (*ListAdminClientsResponse, error)
	AuditUser(context.Context, *AuditUserRequest) (*AuditUserResponse, error)
	AuditChallenge(context.Context, *AuditChallengeRequest) (*AuditEntry, error)
}

// UnimplementedPlatformAdminServiceServer should be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedPlatformAdminServiceServer struct{}

func (UnimplementedPlatformAdminServiceServer) CreateDomain(context.Context, *CreateDomainRequest) (*CreateDomainResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateDomain not implemented")
}
func (UnimplementedPlatformAdminServiceServer) DeleteDomain(context.Context, *DeleteDomainRequest) (*emptypb.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteDomain not implemented")
}
func (UnimplementedPlatformAdminServiceServer) ListDomains(context.Context, *ListDomainsRequest) (*ListDomainsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListDomains not implemented")
}
func (UnimplementedPlatformAdminServiceServer) GetDomain(context.Context, *GetDomainRequest) (*Domain, error) {
	return nil, status.Error(codes.Unimplemented, "method GetDomain not implemented")
}
func (UnimplementedPlatformAdminServiceServer) UpdateDomain(context.Context, *UpdateDomainRequest) (*Domain, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateDomain not implemented")
}
func (UnimplementedPlatformAdminServiceServer) ListAdminClients(context.Context, *ListAdminClientsRequest) (*ListAdminClientsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListAdminClients not implemented")
}
func (UnimplementedPlatformAdminServiceServer) AuditUser(context.Context, *AuditUserRequest) (*AuditUserResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method AuditUser not implemented")
}
func (UnimplementedPlatformAdminServiceServer) AuditChallenge(context.Context, *AuditChallengeRequest) (*AuditEntry, error) {
	return nil, status.Error(codes.Unimplemented, "method AuditChallenge not implemented")
}
func (UnimplementedPlatformAdminServiceServer) testEmbeddedByValue() {}

// UnsafePlatformAdminServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PlatformAdminServiceServer will
// result in compilation errors.
type UnsafePlatformAdminServiceServer interface {
	mustEmbedUnimplementedPlatformAdminServiceServer()
}

func RegisterPlatformAdminServiceServer(s grpc.ServiceRegistrar, srv PlatformAdminServiceServer) {
	// If the following call panics, it indicates UnimplementedPlatformAdminServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&PlatformAdminService_ServiceDesc, srv)
}

func _PlatformAdminService_CreateDomain_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateDomainRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PlatformAdminServiceServer).CreateDomain(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PlatformAdminService_CreateDomain_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PlatformAdminServiceServer).CreateDomain(ctx, req.(*CreateDomainRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PlatformAdminService_DeleteDomain_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteDomainRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PlatformAdminServiceServer).DeleteDomain(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PlatformAdminService_DeleteDomain_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PlatformAdminServiceServer).DeleteDomain(ctx, req.(*DeleteDomainRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PlatformAdminService_ListDomains_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListDomainsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PlatformAdminServiceServer).ListDomains(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PlatformAdminService_ListDomains_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PlatformAdminServiceServer).ListDomains(ctx, req.(*ListDomainsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PlatformAdminService_GetDomain_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetDomainRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PlatformAdminServiceServer).GetDomain(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PlatformAdminService_GetDomain_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PlatformAdminServiceServer).GetDomain(ctx, req.(*GetDomainRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PlatformAdminService_UpdateDomain_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateDomainRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PlatformAdminServiceServer).UpdateDomain(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PlatformAdminService_UpdateDomain_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PlatformAdminServiceServer).UpdateDomain(ctx, req.(*UpdateDomainRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PlatformAdminService_ListAdminClients_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListAdminClientsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PlatformAdminServiceServer).ListAdminClients(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PlatformAdminService_ListAdminClients_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PlatformAdminServiceServer).ListAdminClients(ctx, req.(*ListAdminClientsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PlatformAdminService_AuditUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AuditUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PlatformAdminServiceServer).AuditUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PlatformAdminService_AuditUser_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PlatformAdminServiceServer).AuditUser(ctx, req.(*AuditUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PlatformAdminService_AuditChallenge_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AuditChallengeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PlatformAdminServiceServer).AuditChallenge(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PlatformAdminService_AuditChallenge_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PlatformAdminServiceServer).AuditChallenge(ctx, req.(*AuditChallengeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// PlatformAdminService_ServiceDesc is the grpc.ServiceDesc for PlatformAdminService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var PlatformAdminService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "se.mantra.api.admin.PlatformAdminService",
	HandlerType: (*PlatformAdminServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateDomain",
			Handler:    _PlatformAdminService_CreateDomain_Handler,
		},
		{
			MethodName: "DeleteDomain",
			Handler:    _PlatformAdminService_DeleteDomain_Handler,
		},
		{
			MethodName: "ListDomains",
			Handler:    _PlatformAdminService_ListDomains_Handler,
		},
		{
			MethodName: "GetDomain",
			Handler:    _PlatformAdminService_GetDomain_Handler,
		},
		{
			MethodName: "UpdateDomain",
			Handler:    _PlatformAdminService_UpdateDomain_Handler,
		},
		{
			MethodName: "ListAdminClients",
			Handler:    _PlatformAdminService_ListAdminClients_Handler,
		},
		{
			MethodName: "AuditUser",
			Handler:    _PlatformAdminService_AuditUser_Handler,
		},
		{
			MethodName: "AuditChallenge",
			Handler:    _PlatformAdminService_AuditChallenge_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "service/platform_admin.proto",
}
