// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: service/platform_admin.proto

package admin

import (
	common "github.com/daedaluz/mantra-cli/lib/grpc/common"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateDomainRequest struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	Domain               string                 `protobuf:"bytes,1,opt,name=domain,proto3" json:"domain,omitempty"`
	Name                 string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description          string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Algorithms           []int64                `protobuf:"varint,4,rep,packed,name=algorithms,proto3" json:"algorithms,omitempty"`
	RegistrationPath     string                 `protobuf:"bytes,5,opt,name=registration_path,json=registrationPath,proto3" json:"registration_path,omitempty"`
	SignPath             string                 `protobuf:"bytes,6,opt,name=sign_path,json=signPath,proto3" json:"sign_path,omitempty"`
	RequireDeviceBinding bool                   `protobuf:"varint,7,opt,name=require_device_binding,json=requireDeviceBinding,proto3" json:"require_device_binding,omitempty"`
	TokenMaxAge          int32                  `protobuf:"varint,8,opt,name=token_max_age,json=tokenMaxAge,proto3" json:"token_max_age,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *CreateDomainRequest) Reset() {
	*x = CreateDomainRequest{}
	mi := &file_service_platform_admin_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateDomainRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateDomainRequest) ProtoMessage() {}

func (x *CreateDomainRequest) ProtoReflect() protoreflect.Message {
	mi := &file_service_platform_admin_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateDomainRequest.ProtoReflect.Descriptor instead.
func (*CreateDomainRequest) Descriptor() ([]byte, []int) {
	return file_service_platform_admin_proto_rawDescGZIP(), []int{0}
}

func (x *CreateDomainRequest) GetDomain() string {
	if x != nil {
		return x.Domain
	}
	return ""
}

func (x *CreateDomainRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateDomainRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *CreateDomainRequest) GetAlgorithms() []int64 {
	if x != nil {
		return x.Algorithms
	}
	return nil
}

func (x *CreateDomainRequest) GetRegistrationPath() string {
	if x != nil {
		return x.RegistrationPath
	}
	return ""
}

func (x *CreateDomainRequest) GetSignPath() string {
	if x != nil {
		return x.SignPath
	}
	return ""
}

func (x *CreateDomainRequest) GetRequireDeviceBinding() bool {
	if x != nil {
		return x.RequireDeviceBinding
	}
	return false
}

func (x *CreateDomainRequest) GetTokenMaxAge() int32 {
	if x != nil {
		return x.TokenMaxAge
	}
	return 0
}

type CreateDomainResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ClientId      string                 `protobuf:"bytes,5,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	Secret        string                 `protobuf:"bytes,6,opt,name=secret,proto3" json:"secret,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateDomainResponse) Reset() {
	*x = CreateDomainResponse{}
	mi := &file_service_platform_admin_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateDomainResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateDomainResponse) ProtoMessage() {}

func (x *CreateDomainResponse) ProtoReflect() protoreflect.Message {
	mi := &file_service_platform_admin_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateDomainResponse.ProtoReflect.Descriptor instead.
func (*CreateDomainResponse) Descriptor() ([]byte, []int) {
	return file_service_platform_admin_proto_rawDescGZIP(), []int{1}
}

func (x *CreateDomainResponse) GetClientId() string {
	if x != nil {
		return x.ClientId
	}
	return ""
}

func (x *CreateDomainResponse) GetSecret() string {
	if x != nil {
		return x.Secret
	}
	return ""
}

type DeleteDomainRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Domain        string                 `protobuf:"bytes,1,opt,name=domain,proto3" json:"domain,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteDomainRequest) Reset() {
	*x = DeleteDomainRequest{}
	mi := &file_service_platform_admin_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteDomainRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteDomainRequest) ProtoMessage() {}

func (x *DeleteDomainRequest) ProtoReflect() protoreflect.Message {
	mi := &file_service_platform_admin_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteDomainRequest.ProtoReflect.Descriptor instead.
func (*DeleteDomainRequest) Descriptor() ([]byte, []int) {
	return file_service_platform_admin_proto_rawDescGZIP(), []int{2}
}

func (x *DeleteDomainRequest) GetDomain() string {
	if x != nil {
		return x.Domain
	}
	return ""
}

type Domain struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	Domain               string                 `protobuf:"bytes,1,opt,name=domain,proto3" json:"domain,omitempty"`
	Name                 string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description          string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Algorithms           []int64                `protobuf:"varint,4,rep,packed,name=algorithms,proto3" json:"algorithms,omitempty"`
	CreatedAt            *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	RegistrationPath     string                 `protobuf:"bytes,6,opt,name=registration_path,json=registrationPath,proto3" json:"registration_path,omitempty"`
	SignPath             string                 `protobuf:"bytes,7,opt,name=sign_path,json=signPath,proto3" json:"sign_path,omitempty"`
	RequireDeviceBinding bool                   `protobuf:"varint,8,opt,name=require_device_binding,json=requireDeviceBinding,proto3" json:"require_device_binding,omitempty"`
	TokenMaxAge          int32                  `protobuf:"varint,9,opt,name=token_max_age,json=tokenMaxAge,proto3" json:"token_max_age,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *Domain) Reset() {
	*x = Domain{}
	mi := &file_service_platform_admin_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Domain) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Domain) ProtoMessage() {}

func (x *Domain) ProtoReflect() protoreflect.Message {
	mi := &file_service_platform_admin_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Domain.ProtoReflect.Descriptor instead.
func (*Domain) Descriptor() ([]byte, []int) {
	return file_service_platform_admin_proto_rawDescGZIP(), []int{3}
}

func (x *Domain) GetDomain() string {
	if x != nil {
		return x.Domain
	}
	return ""
}

func (x *Domain) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Domain) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Domain) GetAlgorithms() []int64 {
	if x != nil {
		return x.Algorithms
	}
	return nil
}

func (x *Domain) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Domain) GetRegistrationPath() string {
	if x != nil {
		return x.RegistrationPath
	}
	return ""
}

func (x *Domain) GetSignPath() string {
	if x != nil {
		return x.SignPath
	}
	return ""
}

func (x *Domain) GetRequireDeviceBinding() bool {
	if x != nil {
		return x.RequireDeviceBinding
	}
	return false
}

func (x *Domain) GetTokenMaxAge() int32 {
	if x != nil {
		return x.TokenMaxAge
	}
	return 0
}

type ListDomainsRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Optional filter: if provided, only return domains matching these names
	Domains       []string `protobuf:"bytes,1,rep,name=domains,proto3" json:"domains,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListDomainsRequest) Reset() {
	*x = ListDomainsRequest{}
	mi := &file_service_platform_admin_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListDomainsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListDomainsRequest) ProtoMessage() {}

func (x *ListDomainsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_service_platform_admin_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListDomainsRequest.ProtoReflect.Descriptor instead.
func (*ListDomainsRequest) Descriptor() ([]byte, []int) {
	return file_service_platform_admin_proto_rawDescGZIP(), []int{4}
}

func (x *ListDomainsRequest) GetDomains() []string {
	if x != nil {
		return x.Domains
	}
	return nil
}

type ListDomainsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Domains       []*Domain              `protobuf:"bytes,1,rep,name=domains,proto3" json:"domains,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListDomainsResponse) Reset() {
	*x = ListDomainsResponse{}
	mi := &file_service_platform_admin_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListDomainsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListDomainsResponse) ProtoMessage() {}

func (x *ListDomainsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_service_platform_admin_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListDomainsResponse.ProtoReflect.Descriptor instead.
func (*ListDomainsResponse) Descriptor() ([]byte, []int) {
	return file_service_platform_admin_proto_rawDescGZIP(), []int{5}
}

func (x *ListDomainsResponse) GetDomains() []*Domain {
	if x != nil {
		return x.Domains
	}
	return nil
}

type GetDomainRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Domain        string                 `protobuf:"bytes,1,opt,name=domain,proto3" json:"domain,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDomainRequest) Reset() {
	*x = GetDomainRequest{}
	mi := &file_service_platform_admin_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDomainRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDomainRequest) ProtoMessage() {}

func (x *GetDomainRequest) ProtoReflect() protoreflect.Message {
	mi := &file_service_platform_admin_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDomainRequest.ProtoReflect.Descriptor instead.
func (*GetDomainRequest) Descriptor() ([]byte, []int) {
	return file_service_platform_admin_proto_rawDescGZIP(), []int{6}
}

func (x *GetDomainRequest) GetDomain() string {
	if x != nil {
		return x.Domain
	}
	return ""
}

type UpdateDomainRequest struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	Domain               string                 `protobuf:"bytes,1,opt,name=domain,proto3" json:"domain,omitempty"`
	Name                 string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description          string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Algorithms           []int64                `protobuf:"varint,4,rep,packed,name=algorithms,proto3" json:"algorithms,omitempty"`
	RegistrationPath     string                 `protobuf:"bytes,5,opt,name=registration_path,json=registrationPath,proto3" json:"registration_path,omitempty"`
	SignPath             string                 `protobuf:"bytes,6,opt,name=sign_path,json=signPath,proto3" json:"sign_path,omitempty"`
	RequireDeviceBinding bool                   `protobuf:"varint,7,opt,name=require_device_binding,json=requireDeviceBinding,proto3" json:"require_device_binding,omitempty"`
	TokenMaxAge          int32                  `protobuf:"varint,8,opt,name=token_max_age,json=tokenMaxAge,proto3" json:"token_max_age,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *UpdateDomainRequest) Reset() {
	*x = UpdateDomainRequest{}
	mi := &file_service_platform_admin_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateDomainRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateDomainRequest) ProtoMessage() {}

func (x *UpdateDomainRequest) ProtoReflect() protoreflect.Message {
	mi := &file_service_platform_admin_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateDomainRequest.ProtoReflect.Descriptor instead.
func (*UpdateDomainRequest) Descriptor() ([]byte, []int) {
	return file_service_platform_admin_proto_rawDescGZIP(), []int{7}
}

func (x *UpdateDomainRequest) GetDomain() string {
	if x != nil {
		return x.Domain
	}
	return ""
}

func (x *UpdateDomainRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UpdateDomainRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *UpdateDomainRequest) GetAlgorithms() []int64 {
	if x != nil {
		return x.Algorithms
	}
	return nil
}

func (x *UpdateDomainRequest) GetRegistrationPath() string {
	if x != nil {
		return x.RegistrationPath
	}
	return ""
}

func (x *UpdateDomainRequest) GetSignPath() string {
	if x != nil {
		return x.SignPath
	}
	return ""
}

func (x *UpdateDomainRequest) GetRequireDeviceBinding() bool {
	if x != nil {
		return x.RequireDeviceBinding
	}
	return false
}

func (x *UpdateDomainRequest) GetTokenMaxAge() int32 {
	if x != nil {
		return x.TokenMaxAge
	}
	return 0
}

type ListAdminClientsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Domain        string                 `protobuf:"bytes,1,opt,name=domain,proto3" json:"domain,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListAdminClientsRequest) Reset() {
	*x = ListAdminClientsRequest{}
	mi := &file_service_platform_admin_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListAdminClientsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAdminClientsRequest) ProtoMessage() {}

func (x *ListAdminClientsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_service_platform_admin_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAdminClientsRequest.ProtoReflect.Descriptor instead.
func (*ListAdminClientsRequest) Descriptor() ([]byte, []int) {
	return file_service_platform_admin_proto_rawDescGZIP(), []int{8}
}

func (x *ListAdminClientsRequest) GetDomain() string {
	if x != nil {
		return x.Domain
	}
	return ""
}

type ListAdminClientsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Clients       []*common.ClientMeta   `protobuf:"bytes,1,rep,name=clients,proto3" json:"clients,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListAdminClientsResponse) Reset() {
	*x = ListAdminClientsResponse{}
	mi := &file_service_platform_admin_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListAdminClientsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAdminClientsResponse) ProtoMessage() {}

func (x *ListAdminClientsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_service_platform_admin_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAdminClientsResponse.ProtoReflect.Descriptor instead.
func (*ListAdminClientsResponse) Descriptor() ([]byte, []int) {
	return file_service_platform_admin_proto_rawDescGZIP(), []int{9}
}

func (x *ListAdminClientsResponse) GetClients() []*common.ClientMeta {
	if x != nil {
		return x.Clients
	}
	return nil
}

type AuditUserRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Domain        string                 `protobuf:"bytes,1,opt,name=domain,proto3" json:"domain,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	From          *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=from,proto3" json:"from,omitempty"`
	To            *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=to,proto3" json:"to,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuditUserRequest) Reset() {
	*x = AuditUserRequest{}
	mi := &file_service_platform_admin_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuditUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuditUserRequest) ProtoMessage() {}

func (x *AuditUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_service_platform_admin_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuditUserRequest.ProtoReflect.Descriptor instead.
func (*AuditUserRequest) Descriptor() ([]byte, []int) {
	return file_service_platform_admin_proto_rawDescGZIP(), []int{10}
}

func (x *AuditUserRequest) GetDomain() string {
	if x != nil {
		return x.Domain
	}
	return ""
}

func (x *AuditUserRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *AuditUserRequest) GetFrom() *timestamppb.Timestamp {
	if x != nil {
		return x.From
	}
	return nil
}

func (x *AuditUserRequest) GetTo() *timestamppb.Timestamp {
	if x != nil {
		return x.To
	}
	return nil
}

type AuditChallengeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Domain        string                 `protobuf:"bytes,1,opt,name=domain,proto3" json:"domain,omitempty"`
	ChallengeId   string                 `protobuf:"bytes,2,opt,name=challenge_id,json=challengeId,proto3" json:"challenge_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuditChallengeRequest) Reset() {
	*x = AuditChallengeRequest{}
	mi := &file_service_platform_admin_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuditChallengeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuditChallengeRequest) ProtoMessage() {}

func (x *AuditChallengeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_service_platform_admin_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuditChallengeRequest.ProtoReflect.Descriptor instead.
func (*AuditChallengeRequest) Descriptor() ([]byte, []int) {
	return file_service_platform_admin_proto_rawDescGZIP(), []int{11}
}

func (x *AuditChallengeRequest) GetDomain() string {
	if x != nil {
		return x.Domain
	}
	return ""
}

func (x *AuditChallengeRequest) GetChallengeId() string {
	if x != nil {
		return x.ChallengeId
	}
	return ""
}

type AuditKeyInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	KeyId         []byte                 `protobuf:"bytes,1,opt,name=key_id,json=keyId,proto3" json:"key_id,omitempty"`
	Algorithm     int64                  `protobuf:"varint,2,opt,name=algorithm,proto3" json:"algorithm,omitempty"`
	Revoked       bool                   `protobuf:"varint,3,opt,name=revoked,proto3" json:"revoked,omitempty"`
	Name          string                 `protobuf:"bytes,4,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuditKeyInfo) Reset() {
	*x = AuditKeyInfo{}
	mi := &file_service_platform_admin_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuditKeyInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuditKeyInfo) ProtoMessage() {}

func (x *AuditKeyInfo) ProtoReflect() protoreflect.Message {
	mi := &file_service_platform_admin_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuditKeyInfo.ProtoReflect.Descriptor instead.
func (*AuditKeyInfo) Descriptor() ([]byte, []int) {
	return file_service_platform_admin_proto_rawDescGZIP(), []int{12}
}

func (x *AuditKeyInfo) GetKeyId() []byte {
	if x != nil {
		return x.KeyId
	}
	return nil
}

func (x *AuditKeyInfo) GetAlgorithm() int64 {
	if x != nil {
		return x.Algorithm
	}
	return 0
}

func (x *AuditKeyInfo) GetRevoked() bool {
	if x != nil {
		return x.Revoked
	}
	return false
}

func (x *AuditKeyInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type AuditDeviceInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DeviceId      string                 `protobuf:"bytes,1,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuditDeviceInfo) Reset() {
	*x = AuditDeviceInfo{}
	mi := &file_service_platform_admin_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuditDeviceInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuditDeviceInfo) ProtoMessage() {}

func (x *AuditDeviceInfo) ProtoReflect() protoreflect.Message {
	mi := &file_service_platform_admin_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuditDeviceInfo.ProtoReflect.Descriptor instead.
func (*AuditDeviceInfo) Descriptor() ([]byte, []int) {
	return file_service_platform_admin_proto_rawDescGZIP(), []int{13}
}

func (x *AuditDeviceInfo) GetDeviceId() string {
	if x != nil {
		return x.DeviceId
	}
	return ""
}

func (x *AuditDeviceInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type AuditClientInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ClientId      string                 `protobuf:"bytes,1,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Admin         bool                   `protobuf:"varint,3,opt,name=admin,proto3" json:"admin,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuditClientInfo) Reset() {
	*x = AuditClientInfo{}
	mi := &file_service_platform_admin_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuditClientInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuditClientInfo) ProtoMessage() {}

func (x *AuditClientInfo) ProtoReflect() protoreflect.Message {
	mi := &file_service_platform_admin_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuditClientInfo.ProtoReflect.Descriptor instead.
func (*AuditClientInfo) Descriptor() ([]byte, []int) {
	return file_service_platform_admin_proto_rawDescGZIP(), []int{14}
}

func (x *AuditClientInfo) GetClientId() string {
	if x != nil {
		return x.ClientId
	}
	return ""
}

func (x *AuditClientInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *AuditClientInfo) GetAdmin() bool {
	if x != nil {
		return x.Admin
	}
	return false
}

type AuditEntry struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	ChallengeId       string                 `protobuf:"bytes,1,opt,name=challenge_id,json=challengeId,proto3" json:"challenge_id,omitempty"`
	Title             string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Message           string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	Status            common.Status          `protobuf:"varint,4,opt,name=status,proto3,enum=se.mantra.api.common.Status" json:"status,omitempty"`
	CreatedAt         *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	SignedAt          *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=signed_at,json=signedAt,proto3" json:"signed_at,omitempty"`
	Key               *AuditKeyInfo          `protobuf:"bytes,7,opt,name=key,proto3" json:"key,omitempty"`
	Client            *AuditClientInfo       `protobuf:"bytes,8,opt,name=client,proto3" json:"client,omitempty"`
	Device            *AuditDeviceInfo       `protobuf:"bytes,9,opt,name=device,proto3" json:"device,omitempty"`
	Verified          bool                   `protobuf:"varint,10,opt,name=verified,proto3" json:"verified,omitempty"`
	SignatureLocation *common.Location       `protobuf:"bytes,11,opt,name=signature_location,json=signatureLocation,proto3" json:"signature_location,omitempty"`
	AuthenticatorData []byte                 `protobuf:"bytes,12,opt,name=authenticator_data,json=authenticatorData,proto3" json:"authenticator_data,omitempty"`
	ClientDataJson    []byte                 `protobuf:"bytes,13,opt,name=client_data_json,json=clientDataJson,proto3" json:"client_data_json,omitempty"`
	Signature         []byte                 `protobuf:"bytes,14,opt,name=signature,proto3" json:"signature,omitempty"`
	ExpiresAt         *timestamppb.Timestamp `protobuf:"bytes,15,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *AuditEntry) Reset() {
	*x = AuditEntry{}
	mi := &file_service_platform_admin_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuditEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuditEntry) ProtoMessage() {}

func (x *AuditEntry) ProtoReflect() protoreflect.Message {
	mi := &file_service_platform_admin_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuditEntry.ProtoReflect.Descriptor instead.
func (*AuditEntry) Descriptor() ([]byte, []int) {
	return file_service_platform_admin_proto_rawDescGZIP(), []int{15}
}

func (x *AuditEntry) GetChallengeId() string {
	if x != nil {
		return x.ChallengeId
	}
	return ""
}

func (x *AuditEntry) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *AuditEntry) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *AuditEntry) GetStatus() common.Status {
	if x != nil {
		return x.Status
	}
	return common.Status(0)
}

func (x *AuditEntry) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *AuditEntry) GetSignedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.SignedAt
	}
	return nil
}

func (x *AuditEntry) GetKey() *AuditKeyInfo {
	if x != nil {
		return x.Key
	}
	return nil
}

func (x *AuditEntry) GetClient() *AuditClientInfo {
	if x != nil {
		return x.Client
	}
	return nil
}

func (x *AuditEntry) GetDevice() *AuditDeviceInfo {
	if x != nil {
		return x.Device
	}
	return nil
}

func (x *AuditEntry) GetVerified() bool {
	if x != nil {
		return x.Verified
	}
	return false
}

func (x *AuditEntry) GetSignatureLocation() *common.Location {
	if x != nil {
		return x.SignatureLocation
	}
	return nil
}

func (x *AuditEntry) GetAuthenticatorData() []byte {
	if x != nil {
		return x.AuthenticatorData
	}
	return nil
}

func (x *AuditEntry) GetClientDataJson() []byte {
	if x != nil {
		return x.ClientDataJson
	}
	return nil
}

func (x *AuditEntry) GetSignature() []byte {
	if x != nil {
		return x.Signature
	}
	return nil
}

func (x *AuditEntry) GetExpiresAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ExpiresAt
	}
	return nil
}

type AuditUserResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Entries       []*AuditEntry          `protobuf:"bytes,1,rep,name=entries,proto3" json:"entries,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuditUserResponse) Reset() {
	*x = AuditUserResponse{}
	mi := &file_service_platform_admin_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuditUserResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuditUserResponse) ProtoMessage() {}

func (x *AuditUserResponse) ProtoReflect() protoreflect.Message {
	mi := &file_service_platform_admin_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuditUserResponse.ProtoReflect.Descriptor instead.
func (*AuditUserResponse) Descriptor() ([]byte, []int) {
	return file_service_platform_admin_proto_rawDescGZIP(), []int{16}
}

func (x *AuditUserResponse) GetEntries() []*AuditEntry {
	if x != nil {
		return x.Entries
	}
	return nil
}

var File_service_platform_admin_proto protoreflect.FileDescriptor

const file_service_platform_admin_proto_rawDesc = "" +
	"\n" +
	"\x1cservice/platform_admin.proto\x12\x13se.mantra.api.admin\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1bgoogle/protobuf/empty.proto\x1a\x13common/common.proto\"\xa7\x02\n" +
	"\x13CreateDomainRequest\x12\x16\n" +
	"\x06domain\x18\x01 \x01(\tR\x06domain\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x1e\n" +
	"\n" +
	"algorithms\x18\x04 \x03(\x03R\n" +
	"algorithms\x12+\n" +
	"\x11registration_path\x18\x05 \x01(\tR\x10registrationPath\x12\x1b\n" +
	"\tsign_path\x18\x06 \x01(\tR\bsignPath\x124\n" +
	"\x16require_device_binding\x18\a \x01(\bR\x14requireDeviceBinding\x12\"\n" +
	"\rtoken_max_age\x18\b \x01(\x05R\vtokenMaxAge\"K\n" +
	"\x14CreateDomainResponse\x12\x1b\n" +
	"\tclient_id\x18\x05 \x01(\tR\bclientId\x12\x16\n" +
	"\x06secret\x18\x06 \x01(\tR\x06secret\"-\n" +
	"\x13DeleteDomainRequest\x12\x16\n" +
	"\x06domain\x18\x01 \x01(\tR\x06domain\"\xd5\x02\n" +
	"\x06Domain\x12\x16\n" +
	"\x06domain\x18\x01 \x01(\tR\x06domain\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x1e\n" +
	"\n" +
	"algorithms\x18\x04 \x03(\x03R\n" +
	"algorithms\x129\n" +
	"\n" +
	"created_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x12+\n" +
	"\x11registration_path\x18\x06 \x01(\tR\x10registrationPath\x12\x1b\n" +
	"\tsign_path\x18\a \x01(\tR\bsignPath\x124\n" +
	"\x16require_device_binding\x18\b \x01(\bR\x14requireDeviceBinding\x12\"\n" +
	"\rtoken_max_age\x18\t \x01(\x05R\vtokenMaxAge\".\n" +
	"\x12ListDomainsRequest\x12\x18\n" +
	"\adomains\x18\x01 \x03(\tR\adomains\"L\n" +
	"\x13ListDomainsResponse\x125\n" +
	"\adomains\x18\x01 \x03(\v2\x1b.se.mantra.api.admin.DomainR\adomains\"*\n" +
	"\x10GetDomainRequest\x12\x16\n" +
	"\x06domain\x18\x01 \x01(\tR\x06domain\"\xa7\x02\n" +
	"\x13UpdateDomainRequest\x12\x16\n" +
	"\x06domain\x18\x01 \x01(\tR\x06domain\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x1e\n" +
	"\n" +
	"algorithms\x18\x04 \x03(\x03R\n" +
	"algorithms\x12+\n" +
	"\x11registration_path\x18\x05 \x01(\tR\x10registrationPath\x12\x1b\n" +
	"\tsign_path\x18\x06 \x01(\tR\bsignPath\x124\n" +
	"\x16require_device_binding\x18\a \x01(\bR\x14requireDeviceBinding\x12\"\n" +
	"\rtoken_max_age\x18\b \x01(\x05R\vtokenMaxAge\"1\n" +
	"\x17ListAdminClientsRequest\x12\x16\n" +
	"\x06domain\x18\x01 \x01(\tR\x06domain\"V\n" +
	"\x18ListAdminClientsResponse\x12:\n" +
	"\aclients\x18\x01 \x03(\v2 .se.mantra.api.common.ClientMetaR\aclients\"\x9f\x01\n" +
	"\x10AuditUserRequest\x12\x16\n" +
	"\x06domain\x18\x01 \x01(\tR\x06domain\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12.\n" +
	"\x04from\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\x04from\x12*\n" +
	"\x02to\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\x02to\"R\n" +
	"\x15AuditChallengeRequest\x12\x16\n" +
	"\x06domain\x18\x01 \x01(\tR\x06domain\x12!\n" +
	"\fchallenge_id\x18\x02 \x01(\tR\vchallengeId\"q\n" +
	"\fAuditKeyInfo\x12\x15\n" +
	"\x06key_id\x18\x01 \x01(\fR\x05keyId\x12\x1c\n" +
	"\talgorithm\x18\x02 \x01(\x03R\talgorithm\x12\x18\n" +
	"\arevoked\x18\x03 \x01(\bR\arevoked\x12\x12\n" +
	"\x04name\x18\x04 \x01(\tR\x04name\"B\n" +
	"\x0fAuditDeviceInfo\x12\x1b\n" +
	"\tdevice_id\x18\x01 \x01(\tR\bdeviceId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\"X\n" +
	"\x0fAuditClientInfo\x12\x1b\n" +
	"\tclient_id\x18\x01 \x01(\tR\bclientId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x14\n" +
	"\x05admin\x18\x03 \x01(\bR\x05admin\"\xd7\x05\n" +
	"\n" +
	"AuditEntry\x12!\n" +
	"\fchallenge_id\x18\x01 \x01(\tR\vchallengeId\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\x124\n" +
	"\x06status\x18\x04 \x01(\x0e2\x1c.se.mantra.api.common.StatusR\x06status\x129\n" +
	"\n" +
	"created_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x127\n" +
	"\tsigned_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\bsignedAt\x123\n" +
	"\x03key\x18\a \x01(\v2!.se.mantra.api.admin.AuditKeyInfoR\x03key\x12<\n" +
	"\x06client\x18\b \x01(\v2$.se.mantra.api.admin.AuditClientInfoR\x06client\x12<\n" +
	"\x06device\x18\t \x01(\v2$.se.mantra.api.admin.AuditDeviceInfoR\x06device\x12\x1a\n" +
	"\bverified\x18\n" +
	" \x01(\bR\bverified\x12M\n" +
	"\x12signature_location\x18\v \x01(\v2\x1e.se.mantra.api.common.LocationR\x11signatureLocation\x12-\n" +
	"\x12authenticator_data\x18\f \x01(\fR\x11authenticatorData\x12(\n" +
	"\x10client_data_json\x18\r \x01(\fR\x0eclientDataJson\x12\x1c\n" +
	"\tsignature\x18\x0e \x01(\fR\tsignature\x129\n" +
	"\n" +
	"expires_at\x18\x0f \x01(\v2\x1a.google.protobuf.TimestampR\texpiresAt\"N\n" +
	"\x11AuditUserResponse\x129\n" +
	"\aentries\x18\x01 \x03(\v2\x1f.se.mantra.api.admin.AuditEntryR\aentries2\x83\x06\n" +
	"\x14PlatformAdminService\x12c\n" +
	"\fCreateDomain\x12(.se.mantra.api.admin.CreateDomainRequest\x1a).se.mantra.api.admin.CreateDomainResponse\x12P\n" +
	"\fDeleteDomain\x12(.se.mantra.api.admin.DeleteDomainRequest\x1a\x16.google.protobuf.Empty\x12`\n" +
	"\vListDomains\x12'.se.mantra.api.admin.ListDomainsRequest\x1a(.se.mantra.api.admin.ListDomainsResponse\x12O\n" +
	"\tGetDomain\x12%.se.mantra.api.admin.GetDomainRequest\x1a\x1b.se.mantra.api.admin.Domain\x12U\n" +
	"\fUpdateDomain\x12(.se.mantra.api.admin.UpdateDomainRequest\x1a\x1b.se.mantra.api.admin.Domain\x12o\n" +
	"\x10ListAdminClients\x12,.se.mantra.api.admin.ListAdminClientsRequest\x1a-.se.mantra.api.admin.ListAdminClientsResponse\x12Z\n" +
	"\tAuditUser\x12%.se.mantra.api.admin.AuditUserRequest\x1a&.se.mantra.api.admin.AuditUserResponse\x12]\n" +
	"\x0eAuditChallenge\x12*.se.mantra.api.admin.AuditChallengeRequest\x1a\x1f.se.mantra.api.admin.AuditEntryB/Z-github.com/daedaluz/mantra-cli/lib/grpc/adminb\x06proto3"

var (
	file_service_platform_admin_proto_rawDescOnce sync.Once
	file_service_platform_admin_proto_rawDescData []byte
)

func file_service_platform_admin_proto_rawDescGZIP() []byte {
	file_service_platform_admin_proto_rawDescOnce.Do(func() {
		file_service_platform_admin_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_service_platform_admin_proto_rawDesc), len(file_service_platform_admin_proto_rawDesc)))
	})
	return file_service_platform_admin_proto_rawDescData
}

var file_service_platform_admin_proto_msgTypes = make([]protoimpl.MessageInfo, 17)
var file_service_platform_admin_proto_goTypes = []any{
	(*CreateDomainRequest)(nil),      // 0: se.mantra.api.admin.CreateDomainRequest
	(*CreateDomainResponse)(nil),     // 1: se.mantra.api.admin.CreateDomainResponse
	(*DeleteDomainRequest)(nil),      // 2: se.mantra.api.admin.DeleteDomainRequest
	(*Domain)(nil),                   // 3: se.mantra.api.admin.Domain
	(*ListDomainsRequest)(nil),       // 4: se.mantra.api.admin.ListDomainsRequest
	(*ListDomainsResponse)(nil),      // 5: se.mantra.api.admin.ListDomainsResponse
	(*GetDomainRequest)(nil),         // 6: se.mantra.api.admin.GetDomainRequest
	(*UpdateDomainRequest)(nil),      // 7: se.mantra.api.admin.UpdateDomainRequest
	(*ListAdminClientsRequest)(nil),  // 8: se.mantra.api.admin.ListAdminClientsRequest
	(*ListAdminClientsResponse)(nil), // 9: se.mantra.api.admin.ListAdminClientsResponse
	(*AuditUserRequest)(nil),         // 10: se.mantra.api.admin.AuditUserRequest
	(*AuditChallengeRequest)(nil),    // 11: se.mantra.api.admin.AuditChallengeRequest
	(*AuditKeyInfo)(nil),             // 12: se.mantra.api.admin.AuditKeyInfo
	(*AuditDeviceInfo)(nil),          // 13: se.mantra.api.admin.AuditDeviceInfo
	(*AuditClientInfo)(nil),          // 14: se.mantra.api.admin.AuditClientInfo
	(*AuditEntry)(nil),               // 15: se.mantra.api.admin.AuditEntry
	(*AuditUserResponse)(nil),        // 16: se.mantra.api.admin.AuditUserResponse
	(*timestamppb.Timestamp)(nil),    // 17: google.protobuf.Timestamp
	(*common.ClientMeta)(nil),        // 18: se.mantra.api.common.ClientMeta
	(common.Status)(0),               // 19: se.mantra.api.common.Status
	(*common.Location)(nil),          // 20: se.mantra.api.common.Location
	(*emptypb.Empty)(nil),            // 21: google.protobuf.Empty
}
var file_service_platform_admin_proto_depIdxs = []int32{
	17, // 0: se.mantra.api.admin.Domain.created_at:type_name -> google.protobuf.Timestamp
	3,  // 1: se.mantra.api.admin.ListDomainsResponse.domains:type_name -> se.mantra.api.admin.Domain
	18, // 2: se.mantra.api.admin.ListAdminClientsResponse.clients:type_name -> se.mantra.api.common.ClientMeta
	17, // 3: se.mantra.api.admin.AuditUserRequest.from:type_name -> google.protobuf.Timestamp
	17, // 4: se.mantra.api.admin.AuditUserRequest.to:type_name -> google.protobuf.Timestamp
	19, // 5: se.mantra.api.admin.AuditEntry.status:type_name -> se.mantra.api.common.Status
	17, // 6: se.mantra.api.admin.AuditEntry.created_at:type_name -> google.protobuf.Timestamp
	17, // 7: se.mantra.api.admin.AuditEntry.signed_at:type_name -> google.protobuf.Timestamp
	12, // 8: se.mantra.api.admin.AuditEntry.key:type_name -> se.mantra.api.admin.AuditKeyInfo
	14, // 9: se.mantra.api.admin.AuditEntry.client:type_name -> se.mantra.api.admin.AuditClientInfo
	13, // 10: se.mantra.api.admin.AuditEntry.device:type_name -> se.mantra.api.admin.AuditDeviceInfo
	20, // 11: se.mantra.api.admin.AuditEntry.signature_location:type_name -> se.mantra.api.common.Location
	17, // 12: se.mantra.api.admin.AuditEntry.expires_at:type_name -> google.protobuf.Timestamp
	15, // 13: se.mantra.api.admin.AuditUserResponse.entries:type_name -> se.mantra.api.admin.AuditEntry
	0,  // 14: se.mantra.api.admin.PlatformAdminService.CreateDomain:input_type -> se.mantra.api.admin.CreateDomainRequest
	2,  // 15: se.mantra.api.admin.PlatformAdminService.DeleteDomain:input_type -> se.mantra.api.admin.DeleteDomainRequest
	4,  // 16: se.mantra.api.admin.PlatformAdminService.ListDomains:input_type -> se.mantra.api.admin.ListDomainsRequest
	6,  // 17: se.mantra.api.admin.PlatformAdminService.GetDomain:input_type -> se.mantra.api.admin.GetDomainRequest
	7,  // 18: se.mantra.api.admin.PlatformAdminService.UpdateDomain:input_type -> se.mantra.api.admin.UpdateDomainRequest
	8,  // 19: se.mantra.api.admin.PlatformAdminService.ListAdminClients:input_type -> se.mantra.api.admin.ListAdminClientsRequest
	10, // 20: se.mantra.api.admin.PlatformAdminService.AuditUser:input_type -> se.mantra.api.admin.AuditUserRequest
	11, // 21: se.mantra.api.admin.PlatformAdminService.AuditChallenge:input_type -> se.mantra.api.admin.AuditChallengeRequest
	1,  // 22: se.mantra.api.admin.PlatformAdminService.CreateDomain:output_type -> se.mantra.api.admin.CreateDomainResponse
	21, // 23: se.mantra.api.admin.PlatformAdminService.DeleteDomain:output_type -> google.protobuf.Empty
	5,  // 24: se.mantra.api.admin.PlatformAdminService.ListDomains:output_type -> se.mantra.api.admin.ListDomainsResponse
	3,  // 25: se.mantra.api.admin.PlatformAdminService.GetDomain:output_type -> se.mantra.api.admin.Domain
	3,  // 26: se.mantra.api.admin.PlatformAdminService.UpdateDomain:output_type -> se.mantra.api.admin.Domain
	9,  // 27: se.mantra.api.admin.PlatformAdminService.ListAdminClients:output_type -> se.mantra.api.admin.ListAdminClientsResponse
	16, // 28: se.mantra.api.admin.PlatformAdminService.AuditUser:output_type -> se.mantra.api.admin.AuditUserResponse
	15, // 29: se.mantra.api.admin.PlatformAdminService.AuditChallenge:output_type -> se.mantra.api.admin.AuditEntry
	22, // [22:30] is the sub-list for method output_type
	14, // [14:22] is the sub-list for method input_type
	14, // [14:14] is the sub-list for extension type_name
	14, // [14:14] is the sub-list for extension extendee
	0,  // [0:14] is the sub-list for field type_name
}

func init() { file_service_platform_admin_proto_init() }
func file_service_platform_admin_proto_init() {
	if File_service_platform_admin_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_service_platform_admin_proto_rawDesc), len(file_service_platform_admin_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   17,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_service_platform_admin_proto_goTypes,
		DependencyIndexes: file_service_platform_admin_proto_depIdxs,
		MessageInfos:      file_service_platform_admin_proto_msgTypes,
	}.Build()
	File_service_platform_admin_proto = out.File
	file_service_platform_admin_proto_goTypes = nil
	file_service_platform_admin_proto_depIdxs = nil
}
